/* 간편결제(order-pay) — 실서비스 확장 v1.0 (19화면). 컴포넌트 라이브러리·정적 href·클릭 가능.
 * 메뉴·버튼에서 파생되는 모든 링크가 실제 화면으로 연결됨(빈 링크 0). */
window.PLANDECK_SCREENS = [
  {
    category: '구매 플로우',
    pages: [
      {
        id: 'SCR-HOME-001', label: '상품 목록', href: 'm-home.html',
        surface: 'mobile', entry: true, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-001'],
        context: '앱 첫 화면. 검색·카테고리·상품 카드. 상품 선택 시 상세로. 하단 탭(홈·장바구니·주문·마이).',
        components: [
          { role: '.pd-search', kind: 'button', label: '검색', action: { on: 'click', do: 'go:SCR-SEARCH-001' } },
          { role: '.pd-list', kind: 'list', label: '상품 카드 목록', action: { on: 'click', do: 'go:SCR-DETAIL-001' } },
        ],
        description: [{ text: '검색 → 검색(SCR-SEARCH-001)', target: '.pd-search' }, { text: '상품 선택 → 상세(SCR-DETAIL-001)', target: '.pd-list' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '상품 1건+', result: '카테고리+상품', message: '', target: '.pd-list', api: { endpoint: 'GET /products', status: 200 } },
          { state: '로딩', trigger: '진입', guard: '', result: '스켈레톤', message: '' },
          { state: '빈데이터', trigger: '진입', guard: '0건', result: '안내', message: '상품을 준비 중이에요', placement: 'inline', target: '.pd-list' },
          { state: '에러', trigger: '진입', guard: '서버 오류', result: '재시도', message: '상품을 불러오지 못했어요', placement: 'inline', api: { endpoint: 'GET /products', status: 500 } },
        ],
        interface: { reads: [{ id: 'listProducts', intent: '상품 목록', method: 'GET', path: '/products', params: [{ in: 'query', name: 'category', type: 'string', required: false }], response: '{entities.Product}[]', auth: 'None', target: '.pd-list' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-DETAIL-001', via: '상품 선택', trigger: '.pd-list' }, { screen: 'SCR-SEARCH-001', via: '검색', trigger: '.pd-search' }, { screen: 'SCR-CART-001', via: '장바구니' }, { screen: 'SCR-ORDERS-001', via: '주문(탭)' }, { screen: 'SCR-MYPAGE-001', via: '마이(탭)' }] },
      },
      {
        id: 'SCR-SEARCH-001', label: '검색', href: 'm-search.html',
        surface: 'mobile', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-010'],
        context: '상품 검색. 인기 검색어·검색 결과. 홈 검색바에서 진입.',
        components: [{ role: '.pd-back', kind: 'button', label: '뒤로', action: { on: 'click', do: 'go:SCR-HOME-001' } }],
        description: [{ text: '검색어·인기검색어·결과 목록(→ 상세)' }],
        cases: [
          { state: '정상', trigger: '검색', guard: '결과 1건+', result: '결과 목록', message: '' },
          { state: '빈데이터', trigger: '검색', guard: '0건', result: '안내', message: '검색 결과가 없어요', placement: 'inline' },
        ],
        interface: { reads: [{ id: 'searchProducts', intent: '상품 검색', method: 'GET', path: '/products', params: [{ in: 'query', name: 'q', type: 'string', required: true }], response: '{entities.Product}[]', auth: 'None' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-DETAIL-001', via: '상품 선택' }] },
      },
      {
        id: 'SCR-DETAIL-001', label: '상품 상세', href: 'm-detail.html',
        surface: 'mobile', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-002'],
        context: '상품 이미지·가격·옵션·수량·상세. 장바구니 담기 또는 바로 구매.',
        components: [
          { role: '.pd-back', kind: 'button', label: '뒤로', action: { on: 'click', do: 'go:SCR-HOME-001' } },
          { role: '.pd-add-cart', kind: 'button', label: '장바구니', action: { on: 'click', do: 'go:SCR-CART-001' } },
          { role: '.pd-buy-now', kind: 'button', label: '바로 구매', action: { on: 'click', do: 'go:SCR-CHECKOUT-001' } },
        ],
        description: [{ text: '옵션·수량 선택', target: '.pd-buy-now' }, { text: '장바구니(SCR-CART-001)·바로 구매(SCR-CHECKOUT-001)' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '', result: '상세 표시', message: '', api: { endpoint: 'GET /products/{id}', status: 200 } },
          { state: '에러', trigger: '진입', guard: '품절', result: '구매 비활성', message: '품절된 상품이에요', placement: 'inline', target: '.pd-buy-now' },
          { state: '에러', trigger: '진입', guard: '상품 없음', result: '목록으로', message: '상품을 찾을 수 없어요', placement: 'full-page', api: { endpoint: 'GET /products/{id}', status: 404 } },
        ],
        interface: { reads: [{ id: 'getProduct', intent: '상품 상세', method: 'GET', path: '/products/{id}', response: '{entities.Product}', auth: 'None' }], writes: [{ id: 'addToCart', intent: '장바구니 담기', method: 'POST', path: '/cart/items', auth: 'Guest', target: '.pd-add-cart' }], events: [] },
        flow: { to: [{ screen: 'SCR-CART-001', via: '장바구니', trigger: '.pd-add-cart' }, { screen: 'SCR-CHECKOUT-001', via: '바로 구매', trigger: '.pd-buy-now' }] },
      },
      {
        id: 'SCR-CART-001', label: '장바구니', href: 'm-cart.html',
        surface: 'mobile', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-005'],
        context: '담은 상품·수량 조절·삭제·금액 합계. 주문하기로 주문서 진입.',
        components: [{ role: '.pd-cart-list', kind: 'list', label: '장바구니 상품' }, { role: '.pd-btn-order', kind: 'button', label: '주문하기', action: { on: 'click', do: 'go:SCR-CHECKOUT-001' } }],
        description: [{ text: '상품·수량·금액', target: '.pd-cart-list' }, { text: '주문하기 → 주문서(SCR-CHECKOUT-001)', target: '.pd-btn-order' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '1건+', result: '장바구니·합계', message: '', target: '.pd-cart-list', api: { endpoint: 'GET /cart', status: 200 } },
          { state: '빈데이터', trigger: '진입', guard: '0건', result: '쇼핑 유도', message: '장바구니가 비어 있어요', placement: 'full-page', target: '.pd-cart-list' },
          { state: '정상', trigger: '수량 변경', guard: '', result: '합계 갱신', message: '', target: '.pd-cart-list' },
        ],
        interface: { reads: [{ id: 'getCart', intent: '장바구니', method: 'GET', path: '/cart', response: '{entities.CartItem}[]', auth: 'Guest', target: '.pd-cart-list' }], writes: [{ id: 'updateCart', intent: '수량 변경/삭제', method: 'PATCH', path: '/cart/items/{id}', auth: 'Guest', target: '.pd-cart-list' }], events: [] },
        flow: { to: [{ screen: 'SCR-CHECKOUT-001', via: '주문하기', trigger: '.pd-btn-order' }] },
      },
      {
        id: 'SCR-CHECKOUT-001', label: '주문서', href: 'm-checkout.html',
        surface: 'mobile', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-006'],
        context: '배송지·주문상품·할인(쿠폰/포인트)·결제금액 확인. 결제로 진입.',
        components: [
          { role: '.pd-btn-topay', kind: 'button', label: '결제하기', action: { on: 'click', do: 'go:SCR-PAY-001' } },
        ],
        description: [{ text: '배송지 변경 → 배송지(SCR-ADDRESS-001)' }, { text: '할인 → 쿠폰(SCR-COUPONS-001)' }, { text: '결제하기 → 결제(SCR-PAY-001)', target: '.pd-btn-topay' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '배송지+상품', result: '주문서', message: '', target: '.pd-btn-topay' },
          { state: '필수누락', trigger: '결제하기', guard: '배송지 없음', result: '막음', message: '배송지를 입력해 주세요', placement: 'inline', priority: 'P1' },
        ],
        interface: { reads: [{ id: 'getCheckout', intent: '주문서 조회', method: 'GET', path: '/checkout', response: '{entities.Order}', auth: 'Guest' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PAY-001', via: '결제하기', trigger: '.pd-btn-topay' }, { screen: 'SCR-ADDRESS-001', via: '배송지 변경' }, { screen: 'SCR-COUPONS-001', via: '할인' }] },
      },
      {
        id: 'SCR-ADDRESS-001', label: '배송지 입력', href: 'm-address.html',
        surface: 'mobile', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-006'],
        context: '저장된 배송지 선택 또는 새 배송지 입력(받는분·연락처·주소). 주문서로 복귀.',
        components: [{ role: '.pd-address-form', kind: 'form', label: '배송지 폼', action: { on: 'click', do: 'go:SCR-CHECKOUT-001' } }],
        description: [{ text: '저장 배송지 선택·새 배송지 입력' }],
        cases: [
          { state: '정상', trigger: '선택/입력', guard: '필수', result: '주문서 반영', message: '배송지가 설정됐어요', placement: 'toast' },
          { state: '필수누락', trigger: '저장', guard: '주소 누락', result: '막음', message: '받는 분·주소를 입력해 주세요', placement: 'inline', priority: 'P1' },
        ],
        interface: { reads: [{ id: 'listAddresses', intent: '배송지 목록', method: 'GET', path: '/me/addresses', response: '{entities.Address}[]', auth: 'Guest' }], writes: [{ id: 'saveAddress', intent: '배송지 저장', method: 'POST', path: '/me/addresses', successStatus: 201, request: '{entities.Address}', auth: 'Guest', target: '.pd-address-form' }], events: [] },
        flow: { to: [{ screen: 'SCR-CHECKOUT-001', via: '배송지 설정', kind: 'auto' }] },
      },
      {
        id: 'SCR-PAY-001', label: '결제', href: 'm-pay.html',
        surface: 'mobile', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-003'],
        context: '결제수단 선택(카드/토스페이/카카오페이)·동의·결제 실행. 성공/실패로 분기.',
        components: [
          { role: '.pd-method', kind: 'list', label: '결제수단' },
          { role: '.pd-btn-confirm', kind: 'button', label: '결제하기', action: { on: 'click', do: 'write:createOrder' } },
        ],
        description: [{ text: '결제수단 선택', target: '.pd-method' }, { text: '결제하기 → createOrder → 성공 시 완료(SCR-DONE-001), 실패 시 실패(SCR-FAIL-001)', target: '.pd-btn-confirm' }],
        cases: [
          { state: '정상', trigger: '결제하기', guard: '승인 성공', result: '완료(SCR-DONE-001)', message: '', target: '.pd-btn-confirm', api: { endpoint: 'POST /orders', status: 201 }, priority: 'P0', testId: 'TC-PAY-001' },
          { state: '에러', trigger: '결제하기', guard: '승인 거절', result: '실패(SCR-FAIL-001)', message: '결제가 거절됐어요', placement: 'full-page', api: { endpoint: 'POST /orders', status: 402 }, priority: 'P0', testId: 'TC-PAY-002' },
          { state: '필수누락', trigger: '결제하기', guard: '동의 미체크', result: '막음', message: '결제 동의가 필요해요', placement: 'inline', target: '.pd-btn-confirm', priority: 'P1' },
          { state: '엣지', trigger: '결제하기', guard: '네트워크 끊김', result: '멱등키 재시도', message: '연결이 불안정해요. 다시 시도해 주세요', placement: 'toast' },
        ],
        interface: { reads: [], writes: [{ id: 'createOrder', intent: '주문 생성·결제', method: 'POST', path: '/orders', successStatus: 201, request: '{entities.OrderDraft}', response: '{entities.Order}', errors: [{ status: 402, when: '승인 거절', message: '결제가 거절됐어요' }], auth: 'Guest', idempotency: 'Idempotency-Key', target: '.pd-btn-confirm' }], events: [{ name: 'order.created', when: '결제 성공', payload: '{entities.Order}' }] },
        flow: { to: [{ screen: 'SCR-DONE-001', via: '성공', branch: '결제 성공 여부', onCall: 'createOrder' }, { screen: 'SCR-FAIL-001', via: '실패', branch: '결제 성공 여부' }] },
      },
      {
        id: 'SCR-DONE-001', label: '결제 완료', href: 'm-done.html',
        surface: 'mobile', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-004'],
        context: '결제 성공 안내·주문번호. 주문 상세 또는 홈으로.',
        components: [
          { role: '.pd-btn-detail', kind: 'button', label: '주문 상세', action: { on: 'click', do: 'go:SCR-ORDER-DET-001' } },
          { role: '.pd-btn-home', kind: 'button', label: '홈으로', action: { on: 'click', do: 'go:SCR-HOME-001' } },
        ],
        description: [{ text: '완료 안내·주문번호', target: '.pd-title' }, { text: '주문 상세(SCR-ORDER-DET-001)·홈(SCR-HOME-001)' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '결제 성공', result: '완료 안내+주문번호', message: '결제가 완료됐어요', placement: 'full-page' },
          { state: '에러', trigger: '진입', guard: '주문 없이 직접 진입', result: '홈으로 리다이렉트', message: '', placement: 'full-page' },
        ],
        interface: { reads: [], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-ORDER-DET-001', via: '주문 상세', trigger: '.pd-btn-detail' }, { screen: 'SCR-HOME-001', via: '홈으로', trigger: '.pd-btn-home' }] },
      },
      {
        id: 'SCR-FAIL-001', label: '결제 실패', href: 'm-fail.html',
        surface: 'mobile', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-004'],
        context: '결제 실패 사유 안내. 1탭 재시도 또는 홈으로.',
        components: [
          { role: '.pd-btn-retry', kind: 'button', label: '다시 시도', action: { on: 'click', do: 'go:SCR-PAY-001' } },
          { role: '.pd-btn-home', kind: 'button', label: '홈으로', action: { on: 'click', do: 'go:SCR-HOME-001' } },
        ],
        description: [{ text: '실패 사유·재시도(SCR-PAY-001)·홈' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '결제 실패로 진입', result: '사유 안내', message: '결제에 실패했어요', placement: 'full-page' },
          { state: '정상', trigger: '다시 시도', guard: '', result: '결제 재진입', message: '', target: '.pd-btn-retry' },
        ],
        interface: { reads: [], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PAY-001', via: '다시 시도', trigger: '.pd-btn-retry' }, { screen: 'SCR-HOME-001', via: '홈으로', trigger: '.pd-btn-home' }] },
      },
    ],
  },
  {
    category: '주문 관리',
    pages: [
      {
        id: 'SCR-ORDERS-001', label: '주문 내역', href: 'm-orders.html',
        surface: 'mobile', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-007'],
        context: '주문 목록·배송 상태(배송중/완료/취소). 주문 선택 시 상세, 완료 건은 후기.',
        components: [{ role: '.pd-order-list', kind: 'list', label: '주문 목록', action: { on: 'click', do: 'go:SCR-ORDER-DET-001' } }],
        description: [{ text: '상태 탭·주문 카드(→ 상세, 완료는 후기)', target: '.pd-order-list' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '주문 1건+', result: '주문 목록', message: '', target: '.pd-order-list', api: { endpoint: 'GET /me/orders', status: 200 } },
          { state: '빈데이터', trigger: '진입', guard: '0건', result: '쇼핑 유도', message: '주문 내역이 없어요', placement: 'full-page', target: '.pd-order-list' },
        ],
        interface: { reads: [{ id: 'listOrders', intent: '주문 내역', method: 'GET', path: '/me/orders', params: [{ in: 'query', name: 'status', type: 'string', required: false }], response: '{entities.Order}[]', auth: 'Guest', target: '.pd-order-list' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-ORDER-DET-001', via: '주문 선택', trigger: '.pd-order-list' }, { screen: 'SCR-REVIEW-001', via: '후기' }] },
      },
      {
        id: 'SCR-ORDER-DET-001', label: '주문 상세', href: 'm-order-detail.html',
        surface: 'mobile', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-007'],
        context: '주문 상세·배송 조회(단계)·상품·배송지. 취소/환불·문의로 연결.',
        components: [{ role: '.pd-back', kind: 'button', label: '뒤로', action: { on: 'click', do: 'go:SCR-ORDERS-001' } }, { role: '.pd-btn-refund', kind: 'button', label: '취소/환불', action: { on: 'click', do: 'go:SCR-REFUND-001' } }],
        description: [{ text: '배송 조회·주문 상품·배송지' }, { text: '취소/환불(SCR-REFUND-001)·문의(SCR-SUPPORT-001)' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '', result: '주문 상세·배송단계', message: '', api: { endpoint: 'GET /me/orders/{id}', status: 200 } },
          { state: '엣지', trigger: '진입', guard: '배송 완료', result: '취소 비활성·후기 유도', message: '', placement: 'inline', target: '.pd-btn-refund' },
        ],
        interface: { reads: [{ id: 'getOrder', intent: '주문 상세', method: 'GET', path: '/me/orders/{id}', response: '{entities.Order}', auth: 'Guest' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-REFUND-001', via: '취소/환불', trigger: '.pd-btn-refund' }, { screen: 'SCR-SUPPORT-001', via: '문의하기' }] },
      },
      {
        id: 'SCR-REFUND-001', label: '취소/환불', href: 'm-refund.html',
        surface: 'mobile', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-008'],
        context: '취소 상품·사유 선택·환불 정보 확인·신청. 주문 내역으로 복귀.',
        components: [{ role: '.pd-btn-submit-refund', kind: 'button', label: '취소 신청', action: { on: 'click', do: 'write:requestRefund' } }],
        description: [{ text: '취소 상품·사유·환불 정보' }, { text: '취소 신청 → 주문 내역(SCR-ORDERS-001)', target: '.pd-btn-submit-refund' }],
        cases: [
          { state: '정상', trigger: '신청', guard: '사유 선택·취소 가능', result: '취소 접수', message: '취소를 신청했어요', placement: 'toast', target: '.pd-btn-submit-refund', api: { endpoint: 'POST /me/orders/{id}/refund', status: 201 } },
          { state: '필수누락', trigger: '신청', guard: '사유 미선택', result: '막음', message: '취소 사유를 선택해 주세요', placement: 'inline', priority: 'P1' },
          { state: '범위초과', trigger: '신청', guard: '배송 완료·기한 경과', result: '막음', message: '취소 가능 기간이 지났어요. 고객센터로 문의해 주세요', placement: 'inline', priority: 'P2' },
        ],
        interface: { reads: [], writes: [{ id: 'requestRefund', intent: '취소/환불 신청', method: 'POST', path: '/me/orders/{id}/refund', successStatus: 201, auth: 'Guest', target: '.pd-btn-submit-refund' }], events: [{ name: 'order.refund.requested', when: '취소 신청', payload: '{entities.Order}' }] },
        flow: { to: [{ screen: 'SCR-ORDERS-001', via: '취소 신청', kind: 'auto' }] },
      },
      {
        id: 'SCR-REVIEW-001', label: '후기 작성', href: 'm-review.html',
        surface: 'mobile', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-007'],
        context: '배송 완료 주문에 대한 상품 후기(별점·내용·사진) 작성.',
        components: [{ role: '.pd-review-form', kind: 'form', label: '후기 폼', action: { on: 'click', do: 'go:SCR-ORDERS-001' } }],
        description: [{ text: '별점·후기·사진' }],
        cases: [
          { state: '정상', trigger: '등록', guard: '별점+내용', result: '후기 게시', message: '후기를 등록했어요', placement: 'toast' },
          { state: '필수누락', trigger: '등록', guard: '별점 미선택', result: '막음', message: '별점을 선택해 주세요', placement: 'inline', priority: 'P1' },
        ],
        interface: { reads: [], writes: [{ id: 'createReview', intent: '후기 작성', method: 'POST', path: '/products/{id}/reviews', successStatus: 201, request: '{entities.Review}', auth: 'Guest' }], events: [] },
        flow: { to: [{ screen: 'SCR-ORDERS-001', via: '등록 완료', kind: 'auto' }] },
      },
    ],
  },
  {
    category: '마이·설정',
    pages: [
      {
        id: 'SCR-MYPAGE-001', label: '마이', href: 'm-mypage.html',
        surface: 'mobile', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-009'],
        context: '게스트 구매자 허브 — 주문내역·배송지·결제수단·쿠폰·고객센터.',
        components: [{ role: '.pd-menu', kind: 'list', label: '마이 메뉴', action: { on: 'click', do: 'go:SCR-ORDERS-001' } }],
        description: [{ text: '주문내역·배송지관리·결제수단·쿠폰·고객센터', target: '.pd-menu' }],
        cases: [{ state: '정상', trigger: '진입', guard: '', result: '마이 허브', message: '', target: '.pd-menu' }],
        interface: { reads: [{ id: 'getGuest', intent: '게스트 정보', method: 'GET', path: '/me', response: '{guest}', auth: 'Guest' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-ORDERS-001', via: '주문 내역', trigger: '.pd-menu' }, { screen: 'SCR-ADDRESSBOOK-001', via: '배송지 관리' }, { screen: 'SCR-PAYMENTS-001', via: '결제 수단' }, { screen: 'SCR-COUPONS-001', via: '쿠폰·포인트' }, { screen: 'SCR-SUPPORT-001', via: '고객센터' }] },
      },
      {
        id: 'SCR-PAYMENTS-001', label: '결제 수단 관리', href: 'm-payment-methods.html',
        surface: 'mobile', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-009'],
        context: '등록된 결제 수단 목록·기본 설정·추가.',
        components: [{ role: '.pd-pay-list', kind: 'list', label: '결제수단 목록' }, { role: '.pd-add-pay', kind: 'button', label: '추가', action: { on: 'click', do: 'go:SCR-PAYMENT-ADD-001' } }],
        description: [{ text: '등록 수단·기본·추가(SCR-PAYMENT-ADD-001)' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '1건+', result: '수단 목록', message: '', target: '.pd-pay-list' },
          { state: '빈데이터', trigger: '진입', guard: '0건', result: '추가 유도', message: '등록된 결제 수단이 없어요', placement: 'inline', target: '.pd-pay-list' },
        ],
        interface: { reads: [{ id: 'listPayMethods', intent: '결제수단 목록', method: 'GET', path: '/me/payment-methods', response: '{entities.PaymentMethod}[]', auth: 'Guest', target: '.pd-pay-list' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PAYMENT-ADD-001', via: '추가', trigger: '.pd-add-pay' }] },
      },
      {
        id: 'SCR-PAYMENT-ADD-001', label: '결제 수단 추가', href: 'm-payment-add.html',
        surface: 'mobile', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-009'],
        context: '카드/간편결제 등록(카드번호·유효기간·CVC). 관리 화면으로 복귀.',
        components: [{ role: '.pd-back', kind: 'button', label: '뒤로', action: { on: 'click', do: 'go:SCR-PAYMENTS-001' } }],
        description: [{ text: '카드 정보 입력·등록' }],
        cases: [
          { state: '정상', trigger: '등록', guard: '카드 유효', result: '수단 추가', message: '결제 수단이 등록됐어요', placement: 'toast' },
          { state: '형식오류', trigger: '등록', guard: '카드번호 형식', result: '막음', message: '카드 번호를 확인해 주세요', placement: 'inline', priority: 'P1' },
        ],
        interface: { reads: [], writes: [{ id: 'addPayMethod', intent: '결제수단 등록', method: 'POST', path: '/me/payment-methods', successStatus: 201, request: '{entities.PaymentMethod}', auth: 'Guest' }], events: [] },
        flow: { to: [{ screen: 'SCR-PAYMENTS-001', via: '등록 완료', kind: 'auto' }] },
      },
      {
        id: 'SCR-ADDRESSBOOK-001', label: '배송지 관리', href: 'm-address-book.html',
        surface: 'mobile', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-009'],
        context: '저장된 배송지 목록·기본 설정·수정·추가.',
        components: [{ role: '.pd-addr-list', kind: 'list', label: '배송지 목록' }, { role: '.pd-add-addr', kind: 'button', label: '추가', action: { on: 'click', do: 'go:SCR-ADDRESS-001' } }],
        description: [{ text: '배송지 목록·수정·추가(SCR-ADDRESS-001)' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '1건+', result: '배송지 목록', message: '', target: '.pd-addr-list' },
          { state: '빈데이터', trigger: '진입', guard: '0건', result: '추가 유도', message: '저장된 배송지가 없어요', placement: 'inline', target: '.pd-addr-list' },
        ],
        interface: { reads: [{ id: 'listAddressBook', intent: '배송지 목록', method: 'GET', path: '/me/addresses', response: '{entities.Address}[]', auth: 'Guest', target: '.pd-addr-list' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-ADDRESS-001', via: '추가', trigger: '.pd-add-addr' }] },
      },
      {
        id: 'SCR-COUPONS-001', label: '쿠폰·포인트', href: 'm-coupons.html',
        surface: 'mobile', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-010'],
        context: '보유 포인트·사용 가능 쿠폰·쿠폰 코드 등록.',
        components: [{ role: '.pd-coupon-list', kind: 'list', label: '쿠폰 목록' }],
        description: [{ text: '포인트·쿠폰·코드 등록' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '', result: '포인트·쿠폰', message: '', target: '.pd-coupon-list' },
          { state: '빈데이터', trigger: '진입', guard: '쿠폰 0', result: '안내', message: '사용 가능한 쿠폰이 없어요', placement: 'inline', target: '.pd-coupon-list' },
          { state: '중복충돌', trigger: '코드 등록', guard: '이미 등록', result: '막음', message: '이미 등록된 쿠폰이에요', placement: 'inline', priority: 'P2' },
        ],
        interface: { reads: [{ id: 'listCoupons', intent: '쿠폰·포인트', method: 'GET', path: '/me/coupons', auth: 'Guest', target: '.pd-coupon-list' }], writes: [{ id: 'registerCoupon', intent: '쿠폰 등록', method: 'POST', path: '/me/coupons', auth: 'Guest' }], events: [] },
        flow: { to: [] },
      },
      {
        id: 'SCR-SUPPORT-001', label: '고객센터', href: 'm-support.html',
        surface: 'mobile', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-010'],
        context: 'FAQ·1:1 문의·전화 상담. 검색으로 도움말 탐색.',
        components: [{ role: '.pd-faq-list', kind: 'list', label: 'FAQ 목록' }],
        description: [{ text: 'FAQ·1:1 문의·전화 상담' }],
        cases: [{ state: '정상', trigger: '진입', guard: '', result: 'FAQ·문의 채널', message: '', target: '.pd-faq-list' }],
        interface: { reads: [{ id: 'listFaq', intent: '자주 묻는 질문(FAQ) 조회', method: 'GET', path: '/support/faq', auth: 'None', target: '.pd-faq-list' }], writes: [], events: [] },
        flow: { to: [] },
      },
    ],
  },
];
window.PDK_SCREENS = window.PLANDECK_SCREENS;
