window.PLANDECK_PRD = {
  version: '1.1.4',
  background: '소규모 교회(예장통합 100명 이하 72%)는 재정·인력난으로 자체 앱·홈페이지를 갖기 어렵고, 기존 공용 입주형 앱은 교회 고유 브랜드를 담지 못한다. 훌메이트는 한 코드베이스(화이트라벨 멀티테넌트)로 교회마다 독립 브랜드의 교인앱·공개홈·관리자콘솔을 30분 내 발행하고 유지비를 최소화한다. 은성교회를 1호 파일럿으로 검증한다.',
  goals: [
    '교회별 독립 브랜드 앱(교인앱·공개홈)을 코드 복제 없이 설정값만으로 발행',
    '목회자가 콘솔에서 설교·공지·성도를 직접 관리(개발자 없이 운영)',
    '개인정보보호(PIPA)를 기본 내장 — "가입만 해도 법 준수"',
    '파일럿(은성) 기준 공개홈·교인앱 운영 품질 달성',
  ],
  users: [
    { role: '교인(성도)', jobStory: '우리 교회 앱에서 설교를 보고 공지·헌금안내를 확인하고, 내 영수증·출석·개인정보를 스스로 관리하고 싶다' },
    { role: '목회자/관리자', jobStory: '개발자 없이 설교·성도·공지·공개홈을 직접 관리하고 현황을 보고 싶다' },
    { role: '방문자(새가족)', jobStory: '교회 공개 홈에서 예배 시간·오시는 길·분위기를 알고 싶다' },
    { role: '플랫폼 운영자', jobStory: '여러 교회(테넌트)를 한 플랫폼에서 안전하게 운영·분리·심사·과금하고 싶다' },
  ],
  scope: [
    '교인앱(모바일 PWA): 홈·설교·헌금안내·마이·커뮤니티·아나바다·교회학교·주보·성도매장·알림·설정·검색·출석(QR/온라인)·영수증 조회·개인정보 권리요청·약관/처리방침',
    '공개홈(모바일): 환영/말씀/공동체/콘텐츠형 4템플릿·예배안내·교회소개·교역자·위치·설교·새가족·소식·법적 고지',
    '관리자콘솔(PC웹): 대시보드·성도관리·출석·설교·공지·재정·문자지갑·PIPA·홈페이지·공개홈 콘텐츠 관리·UGC 모더레이션·로그인/계정',
    '슈퍼관리자(PC웹): 테넌트·심사·구독/플랜·도메인·감사로그·로그인',
    '화이트라벨: 테넌트별 브랜드(색·로고)·기능 On/Off·공개홈 템플릿 4종',
  ],
  outOfScope: [
    '헌금 실 PG 결제(파일럿=안내전용)',
    '정기구독(교인 대상)·다국어(i18n)',
    '실시간 채팅상담·성도 간 1:1 메시지',
  ],
  successMetrics: [
    { metric: '파일럿 공개홈·교인앱 운영 품질', target: '은성 실데이터로 실렌더 합격' },
    { metric: 'SOM(3년)', target: '1,000교회 · 구독 ARR 4.8억(목표)' },
    { metric: '발행 소요', target: '교회 1곳 30분 내 브랜드 앱 발행' },
    { metric: '접근성', target: 'WCAG 2.1 AA(고령 교인 필수 게이트)' },
  ],
  constraints: [
    '멀티테넌트 격리 — 모든 조회·쓰기는 교회(tenant) 스코프 강제(아래 tenancy)',
    'PIPA 내장 — 민감정보(주민번호) 전용권한·암호화·마스킹, 동의 원장, 14세 미만 법정대리인 동의, 권리행사 경로',
    '정직성 — 미확보 콘텐츠(계좌·영상·연혁)는 "교회 확인 후 게재" placeholder(임의기재 금지)',
    '되돌리기 어려운 쓰기(영수증·대량발송·테넌트발행·승인)는 멱등키·확인·취소·감사로그 필수',
  ],
  assumptions: [
    '교인은 스마트폰(모바일) 중심, 관리자는 PC웹 중심',
    '설교 영상은 유튜브 URL 연동(자체 호스팅 아님)',
    '비회원도 slug/도메인으로 공개홈 접근, 교인은 로그인 후 앱',
  ],
  dependencies: [
    'platform-db churchhub 스키마(멀티테넌트·RLS)',
    '화이트라벨 엔진(테넌트 라우팅·동적 manifest·테마 주입)',
    '외부: 유튜브(설교 메타·라이브) · FCM/Web Push · 문자발송사 · DNS 확인 · (차기)PG',
  ],
  releases: [
    { name: 'Pilot(은성 1호)', scope: ['공개홈', '교인앱', '관리자 대시보드·성도관리'], when: '파일럿' },
    { name: 'Phase 0 MVP', scope: ['출석(QR/온라인)', '전자기부금영수증', '문자지갑', 'PIPA 권리요청', '로그인·법적문서'], when: '파일럿 후' },
    { name: 'Phase 1', scope: ['공개홈 4템플릿·콘텐츠 관리', 'UGC 모더레이션', '구독/과금', '감사로그'], when: 'MVP 후' },
  ],
  // ── 비기능 요구사항(NFR) ──
  nfr: {
    accessibility: ['WCAG 2.1 AA', '고령 교인 대상 — 본문 16px+·글자크기 조절·명암 대비 4.5:1·터치 타깃 44px+·스크린리더 레이블·폼 에러 음성안내'],
    pwa: ['서비스워커 오프라인 캐싱·앱 설치 유도·업데이트 알림·오프라인 fallback 화면', 'iOS Safari PWA 푸시 제약 고지'],
    push: ['Web Push(FCM)·권한요청 UX·수신동의 연계(PIPA)·야간발송 제한(21~08시)·카테고리별 수신설정'],
    security: ['JWT 인증·HTTPS 전용·민감정보 AES 암호화·비번정책(8자+복잡도)·감사로그 보존 3년·로그인 실패 제한'],
    performance: ['주일 예배 트래픽 스파이크 대비·홈 응답 <1s·설교목록 <2s·CDN·이미지 최적화'],
    availability: ['99.5% 가동·일 백업·DR 절차', '지원 브라우저: 최신 Chrome/Safari/Samsung Internet'],
  },
  // ── 권한 모델(RBAC) — role(직분) × permission(기능) 2축 ──
  rbac: {
    roles: ['member(일반 교인)', 'staff(교역자·직원)', 'pastor(담임목사)', 'admin(교회 관리자)', 'super(플랫폼 운영자)'],
    permissions: ['finance.read', 'finance.write', 'pii.read', 'member.approve', 'message.send', 'homepage.edit', 'content.edit', 'moderate'],
    matrix: [
      { who: 'member', can: '본인 정보·영수증 조회·권리요청·출석·알림설정·커뮤니티 작성' },
      { who: 'staff', can: '설교·공지·공개홈 콘텐츠 작성(content.edit)' },
      { who: 'pastor', can: 'staff 전체 + 성도 조회 + 가입 승인(member.approve)' },
      { who: 'admin', can: '성도관리·승인·권한 위임·홈페이지(homepage.edit)·공지·모더레이션(moderate)' },
      { who: 'admin + finance', can: '재정·영수증 발급(finance.read/write)' },
      { who: 'admin + privacy', can: '민감정보 열람(pii.read)·권리요청 처리' },
      { who: 'super', can: '테넌트 발행·심사·구독·도메인·감사로그(교차테넌트 — 전 접근 감사기록)' },
    ],
    note: 'pii.read·finance·message.send는 명시 위임 권한 필요. 모든 교차테넌트 접근은 audit 로그.',
  },
  // ── 멀티테넌트 스코핑 계약 ──
  tenancy: {
    isolation: '모든 조회·쓰기는 tenantId 스코프 강제. DB Row-Level Security(RLS) + 앱레벨 필터 이중 방어.',
    identification: 'app/admin API는 JWT의 tenantId claim으로 테넌트 판별(path에 노출 X). 공개홈(site)은 slug(?tenant=) 또는 custom domain으로 판별.',
    crossTenant: '슈퍼관리자만 교차테넌트 접근 가능, 모든 접근은 감사로그(audit)에 memberId·대상·시각 기록.',
    offboarding: '교회 해지 시 데이터 반출(export) 제공 후 파기(PIPA·데이터 주권). 유예기간 30일.',
  },
  // ── 대체재·지불의사(전략 하방 방어) ──
  alternatives: {
    competitors: [
      { name: '네이버 밴드', cost: '무료', gap: '교회 전용 아님·브랜드 없음·설교/헌금/교적/영수증 미지원·광고' },
      { name: '카카오톡 채널', cost: '무료', gap: '공지 일방향·커뮤니티/관리/교적 없음·브랜드 약함' },
      { name: '유튜브', cost: '무료', gap: '설교 송출만·공동체/관리/개인정보 전무' },
      { name: '공용 입주형 교회앱', cost: '유료', gap: '교회 고유 브랜드 없음(공용 틀)·커스터마이즈 제한·PIPA 부담 전가' },
    ],
    differentiation: ['교회별 독립 브랜드 앱(화이트라벨)', 'PIPA 기본 내장(가입만 해도 준수)', '30분 발행·개발자 없이 운영', '교적·출석·영수증·헌금·공개홈 통합'],
    wtp: '월 3~5만(개교회 예산 내). 전환 트리거 = 개인정보보호법 부담·독립 브랜드 필요·공용앱 불만. 은성 파일럿 유료전환 의사로 1차 검증.',
    risk: '무료 대체재(밴드) 대비 WTP가 핵심 하방 → 파일럿 WTP 증거 확보 전 대규모 투입 금지(비대칭 하방 방어).',
  },
  requirements: [
    { reqId: 'REQ-001', text: '교인은 앱 홈에서 이번 주 설교·공지·바로가기를 본다', surfaces: ['app'] },
    { reqId: 'REQ-002', text: '교인은 설교를 재생하고, 관리자는 설교를 등록·라이브 토글한다', surfaces: ['app', 'admin'] },
    { reqId: 'REQ-003', text: '교인은 헌금 종류·계좌 안내를 확인한다(안내전용)', surfaces: ['app'] },
    { reqId: 'REQ-004', text: '교인은 로그인·마이에서 내 정보를 보고, 가입은 승인대기로 처리된다', surfaces: ['app'] },
    { reqId: 'REQ-005', text: '방문자/교인은 공개 환영형 홈·공개 설교를 본다', surfaces: ['site'] },
    { reqId: 'REQ-006', text: '방문자는 예배 시간·부서·오시는 길을 확인한다', surfaces: ['site'] },
    { reqId: 'REQ-007', text: '관리자는 대시보드에서 성도·출석·헌금 현황을 본다', surfaces: ['admin'] },
    { reqId: 'REQ-008', text: '관리자는 성도(교적)를 카드·직분·이력으로 관리하고, 가입을 승인/거부한다', surfaces: ['admin'] },
    { reqId: 'REQ-009', text: '관리자는 예배별 출석을 체크하고 장기결석을 자동 감지한다', surfaces: ['admin'] },
    { reqId: 'REQ-010', text: '관리자는 헌금을 집계하고 전자기부금영수증을 발급한다(PIPA·세무·멱등)', surfaces: ['admin'] },
    { reqId: 'REQ-011', text: '교인은 커뮤니티(나눔터)에서 기도제목·간증을 나눈다', surfaces: ['app'] },
    { reqId: 'REQ-012', text: '교인은 아나바다(중고나눔)·성도매장을 이용한다', surfaces: ['app'] },
    { reqId: 'REQ-013', text: '교인은 교회학교 부서별 공지·일정을 본다', surfaces: ['app'] },
    { reqId: 'REQ-014', text: '교인은 주간 주보를 열람한다', surfaces: ['app'] },
    { reqId: 'REQ-015', text: '방문자는 교회 소개·섬기는 사람들·소식을 본다', surfaces: ['site'] },
    { reqId: 'REQ-016', text: '방문자는 새가족 안내를 보고 동의 기반으로 등록한다(PIPA)', surfaces: ['site'] },
    { reqId: 'REQ-017', text: '관리자는 공개홈 템플릿·브랜드(색·로고)를 설정한다(화이트라벨)', surfaces: ['admin'] },
    { reqId: 'REQ-018', text: '플랫폼 운영자는 교회(테넌트)를 발행·구독·심사 관리한다', surfaces: ['super'] },
    { reqId: 'REQ-019', text: '교인은 문자/푸시 알림을 받고, 관리자는 문자지갑을 관리한다(옵트아웃·야간제한)', surfaces: ['app', 'admin'] },
    { reqId: 'REQ-020', text: '관리자는 PIPA 동의 원장·개인정보 권리요청을 처리한다', surfaces: ['admin'] },
    { reqId: 'REQ-021', text: '교인은 개인정보 권리요청(열람·정정·삭제·처리정지)을 직접 제출한다', surfaces: ['app'] },
    { reqId: 'REQ-022', text: '교인은 본인 기부금영수증을 조회하고 발급을 요청·다운로드한다(발급 주체=교회)', surfaces: ['app'] },
    { reqId: 'REQ-023', text: '교인은 QR 또는 온라인 시청으로 출석한다', surfaces: ['app'] },
    { reqId: 'REQ-024', text: '교인은 알림 수신설정(카테고리별 on/off)을 관리한다(수신동의 연계)', surfaces: ['app'] },
    { reqId: 'REQ-025', text: '관리자·운영자는 로그인하고 비밀번호를 재설정한다', surfaces: ['admin', 'super'] },
    { reqId: 'REQ-026', text: '사용자는 이용약관·개인정보처리방침을 열람하고 가입 시 동의한다', surfaces: ['app', 'site'] },
    { reqId: 'REQ-027', text: '관리자는 공개홈 콘텐츠(예배·소개·교역자·위치·소식)를 직접 관리한다', surfaces: ['admin'] },
    { reqId: 'REQ-028', text: '공개홈은 4가지 템플릿(환영/말씀/공동체/콘텐츠형)으로 발행된다', surfaces: ['site'] },
    { reqId: 'REQ-029', text: '교인은 설정(알림·글자크기·앱정보·회원탈퇴=개인정보 파기)을 관리한다', surfaces: ['app'] },
    { reqId: 'REQ-030', text: '사용자는 설교·성도·콘텐츠를 검색한다', surfaces: ['app', 'admin'] },
    { reqId: 'REQ-031', text: '관리자는 UGC(커뮤니티·댓글·아나바다·매장)를 모더레이션(신고·차단·승인)한다', surfaces: ['admin'] },
    { reqId: 'REQ-032', text: '운영자는 교차테넌트 접근·민감정보 열람 감사로그를 조회한다', surfaces: ['super'] },
    { reqId: 'REQ-033', text: '운영자는 구독 플랜·해지·환불·연체 정책을 관리한다', surfaces: ['super'] },
  ],
  workflows: [
    { name: '교인 설교 시청', steps: ['앱 홈', '설교 상세', '헌금 안내'] },
    { name: '교인 가입·동의', steps: ['회원가입', '약관/처리방침 동의', '승인대기'] },
    { name: '교인 셀프서비스', steps: ['마이', '영수증 조회', '권리요청·알림설정'] },
    { name: '방문자 공개홈', steps: ['공개 환영형 홈', '예배 안내', '오시는 길'] },
    { name: '관리자 운영', steps: ['관리자 대시보드', '성도관리(승인/거부)', '출석 관리'] },
    { name: '설교 발행', steps: ['설교 관리', '교인앱 홈', '설교 상세'] },
    { name: '공개홈 운영', steps: ['공개홈 콘텐츠 관리', '홈페이지 설정', '공개 환영형 홈'] },
    { name: '화이트라벨 발행', steps: ['테넌트 관리', '교회 발행', '이단심사 게이트'] },
    { name: '운영 관리', steps: ['구독·과금', '감사로그', '커스텀 도메인'] },
  ],
  openQuestions: [],
  resolvedDecisions: [
    '요금 = 월 3~5만(플랜별). 애드온(문자 충전·추가 용량) 별도 — 구독 관리(SCR-SUP-005)',
    '푸시 = FCM/Web Push, iOS PWA 제약 고지. 실결제(PG)는 차기(현 안내전용)',
    'RBAC = role(직분)+permission(기능 위임) 2축, 민감/재정/발송은 명시 위임',
    '멀티테넌트 = JWT tenantId claim + DB RLS, 슈퍼 교차접근은 감사로그',
  ],
  // 개발 착수 전 기획자 결재 권고(규제·결제·대외발송) — docs/PRD.md ⑮ J-게이트 미러
  jGate: [
    'PIPA — 민감정보(주민번호)·14세 미만 법정대리인 동의·처리방침/동의서·처리위탁 고지 — 법무 검토',
    '전자기부금영수증(세무) — 발급 정확성·취소·보존 — 되돌리기 어려움',
    '대외 발송(문자/푸시) — 수신동의·옵트아웃·야간발송 제한',
    '헌금 계좌 안내 / 향후 PG — 유사수신·전자금융 규제 경계',
    '이단심사 게이트 — 종교 차별 소지 — 심사 기준·주체·이의절차 사전 합의',
  ],
};
window.PDK_PRD = window.PLANDECK_PRD;
