/* 훌메이트 데이터 모델 — 모든 엔티티는 tenantId(교회) 스코프로 격리(멀티테넌트).
 * 권한: Member.role(조직 직분) + Member.permissions(기능 권한) 2축. 매트릭스는 PRD 참조. */
window.PLANDECK_ENTITIES = {
  Church: {
    name: '교회(테넌트)', description: '화이트라벨 테넌트 — 교회별 독립 브랜드·설정. 모든 데이터의 격리 단위',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true, example: 'chr_eunsung' },
      { name: 'slug', type: 'string', required: true, example: 'eunsung', note: 'URL 경로 테넌트 식별자' },
      { name: 'name', type: 'string', required: true, example: '은성교회' },
      { name: 'homeConcept', type: 'string', enum: ['welcome', 'sermon', 'community', 'content'], required: true, example: 'welcome', note: '공개홈 디자인 템플릿(4종)' },
      { name: 'theme', type: 'object', note: '브랜드 색·로고(화이트라벨)', example: { primary: '#53634b', logo: '/eunsung/logo.png' } },
      { name: 'features', type: 'object', note: '기능 On/Off 플래그', example: { finance: true, registry: false, market: false } },
      { name: 'offeringGuideOnly', type: 'boolean', example: true, note: '헌금=안내전용(실결제 X)' },
      { name: 'reviewStatus', type: 'string', enum: ['pending', 'approved', 'rejected'], required: true, note: '이단심사 게이트 — approved만 노출' },
      { name: 'status', type: 'string', enum: ['provisioning', 'active', 'suspended', 'offboarding'], required: true, note: '구독·운영 상태' },
    ],
  },
  Member: {
    name: '성도(교인)', description: '교회 소속 성도 — 테넌트 격리. 민감정보 PIPA 내장. role(직분)+permissions(기능권한) 2축',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'tenantId', type: 'string', format: 'uuid', required: true, note: '교회(테넌트) 스코프' },
      { name: 'name', type: 'string', required: true, example: '김성도' },
      { name: 'role', type: 'string', enum: ['member', 'staff', 'pastor', 'admin'], required: true, example: 'member', note: '직분: 일반/교역자·직원/담임목사/교회관리자' },
      { name: 'permissions', type: 'array', note: '기능 권한(admin이 위임). 값: finance.read·finance.write·pii.read·member.approve·message.send·homepage.edit·content.edit', example: ['member.approve'] },
      { name: 'status', type: 'string', enum: ['pending', 'active', 'rejected', 'withdrawn'], required: true, example: 'active', note: '가입=승인대기 흐름. withdrawn=탈퇴(PIPA 파기)' },
      { name: 'department', type: 'string', example: '청년부' },
      { name: 'rrnEnc', type: 'string', note: '주민번호 암호문 — pii.read 권한 전용·마스킹(PIPA)', example: '••••••-•••••••' },
      { name: 'isMinor', type: 'boolean', example: false, note: '14세 미만=법정대리인 동의 필수(PIPA)' },
    ],
  },
  PlatformAdmin: {
    name: '플랫폼 운영자(슈퍼)', description: '테넌트 무관 플랫폼 운영자 — 교차테넌트 접근은 감사로그 필수',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'email', type: 'string', format: 'email', required: true },
      { name: 'scope', type: 'string', enum: ['tenant_ops', 'review', 'billing', 'super'], required: true, note: '교차테넌트 접근 범위' },
    ],
  },
  Sermon: {
    name: '설교', description: '설교 콘텐츠(유튜브 URL 파싱 → 앱 재생). 주일 라이브 토글',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'tenantId', type: 'string', format: 'uuid', required: true },
      { name: 'title', type: 'string', required: true, example: '로마서 강해 12' },
      { name: 'preacher', type: 'string', required: true, example: '조정표 담임목사' },
      { name: 'videoUrl', type: 'string', format: 'uri', example: 'https://youtu.be/…' },
      { name: 'series', type: 'string', example: '로마서 강해' },
      { name: 'date', type: 'string', format: 'date', required: true },
      { name: 'visibility', type: 'string', enum: ['public', 'members'], required: true, example: 'public', note: '공개홈 노출 여부' },
      { name: 'isLive', type: 'boolean', example: false, note: '주일 라이브=홈 노출' },
    ],
  },
  Offering: {
    name: '헌금(안내)', description: '헌금 안내 정보 — 파일럿은 안내전용(실 PG 결제 미연동)',
    fields: [
      { name: 'tenantId', type: 'string', format: 'uuid', required: true },
      { name: 'kinds', type: 'array', required: true, example: ['주정헌금', '십일조', '감사헌금'] },
      { name: 'account', type: 'string', example: '○○은행 000-000-000000', note: '미제공 시 교회확인후게재' },
      { name: 'guideOnly', type: 'boolean', required: true, example: true },
    ],
  },
  Receipt: {
    name: '기부금영수증', description: '전자기부금영수증(연말정산·세무). ★되돌리기 어려움 — 발급 멱등·감사추적',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'tenantId', type: 'string', format: 'uuid', required: true },
      { name: 'memberId', type: 'string', format: 'uuid', required: true },
      { name: 'year', type: 'integer', required: true, example: 2026 },
      { name: 'amount', type: 'integer', required: true, example: 2400000, note: '연간 헌금 합계(원)' },
      { name: 'status', type: 'string', enum: ['issued', 'reissued', 'canceled'], required: true },
      { name: 'pdfUrl', type: 'string', format: 'uri' },
      { name: 'issuedAt', type: 'string', format: 'date-time', required: true },
    ],
  },
  AttendanceSession: {
    name: '출석 세션', description: '예배별 출석 체크 세션(관리자) — 장기결석 자동감지 기반',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'tenantId', type: 'string', format: 'uuid', required: true },
      { name: 'service', type: 'string', required: true, example: '주일 1부 예배' },
      { name: 'date', type: 'string', format: 'date', required: true },
      { name: 'qrToken', type: 'string', note: '교인 QR 출석용 1회성 토큰' },
      { name: 'presentCount', type: 'integer', example: 42 },
      { name: 'method', type: 'string', enum: ['qr', 'manual', 'online'], example: 'qr', note: '온라인예배 시청=출석 자동인정' },
    ],
  },
  Notice: {
    name: '공지', description: '공지·홈 배너. 노출기간·우선순위',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'tenantId', type: 'string', format: 'uuid', required: true },
      { name: 'title', type: 'string', required: true },
      { name: 'body', type: 'string', required: true },
      { name: 'isBanner', type: 'boolean', example: true },
      { name: 'showFrom', type: 'string', format: 'date' },
      { name: 'showTo', type: 'string', format: 'date' },
      { name: 'status', type: 'string', enum: ['draft', 'published', 'hidden'], required: true },
    ],
  },
  Post: {
    name: '커뮤니티 글', description: '나눔터 게시(기도제목·간증·소그룹). UGC — 모더레이션 대상',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'tenantId', type: 'string', format: 'uuid', required: true },
      { name: 'authorId', type: 'string', format: 'uuid', required: true },
      { name: 'category', type: 'string', enum: ['prayer', 'testimony', 'group', 'share'], required: true },
      { name: 'title', type: 'string', required: true },
      { name: 'body', type: 'string', required: true },
      { name: 'anonymous', type: 'boolean', example: false },
      { name: 'status', type: 'string', enum: ['visible', 'reported', 'hidden'], required: true, note: '신고/차단 모더레이션' },
      { name: 'commentCount', type: 'integer', example: 3 },
    ],
  },
  Comment: {
    name: '댓글', description: '커뮤니티 글 댓글. UGC — 모더레이션 대상',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'tenantId', type: 'string', format: 'uuid', required: true },
      { name: 'postId', type: 'string', format: 'uuid', required: true },
      { name: 'authorId', type: 'string', format: 'uuid', required: true },
      { name: 'body', type: 'string', required: true },
      { name: 'status', type: 'string', enum: ['visible', 'reported', 'hidden'], required: true },
    ],
  },
  Item: {
    name: '나눔 물품(아나바다)', description: '성도 간 중고 나눔(무료·나눔). UGC — 분쟁 면책·모더레이션',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'tenantId', type: 'string', format: 'uuid', required: true },
      { name: 'sellerId', type: 'string', format: 'uuid', required: true },
      { name: 'title', type: 'string', required: true },
      { name: 'photos', type: 'array', note: '사진 URL[]' },
      { name: 'condition', type: 'string', enum: ['상', '중', '하'], example: '상' },
      { name: 'status', type: 'string', enum: ['available', 'reserved', 'done', 'hidden'], required: true },
    ],
  },
  Store: {
    name: '성도 매장', description: '성도 생업 홍보 디렉터리. 등록→관리자 승인→노출',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'tenantId', type: 'string', format: 'uuid', required: true },
      { name: 'ownerId', type: 'string', format: 'uuid', required: true },
      { name: 'name', type: 'string', required: true, example: '은혜베이커리' },
      { name: 'category', type: 'string', example: '제과제빵' },
      { name: 'contact', type: 'string', example: '031-000-0000' },
      { name: 'status', type: 'string', enum: ['pending', 'approved', 'rejected'], required: true },
    ],
  },
  Bulletin: {
    name: '주보', description: '주간 주보(예배순서·광고·헌금·일정). 관리자 발행',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'tenantId', type: 'string', format: 'uuid', required: true },
      { name: 'week', type: 'string', format: 'date', required: true, note: '주차(주일 날짜)' },
      { name: 'fileUrl', type: 'string', format: 'uri' },
      { name: 'publishedAt', type: 'string', format: 'date-time' },
    ],
  },
  EduPost: {
    name: '교회학교 콘텐츠', description: '부서별 공지·일정·자료',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'tenantId', type: 'string', format: 'uuid', required: true },
      { name: 'department', type: 'string', enum: ['유치부', '아동부', '중고등부', '청년부'], required: true },
      { name: 'title', type: 'string', required: true },
      { name: 'body', type: 'string' },
      { name: 'scheduleDate', type: 'string', format: 'date' },
    ],
  },
  SiteContent: {
    name: '공개홈 콘텐츠', description: '공개홈 노출 데이터(예배시간·교회소개·교역자·위치·소식). 관리자 CRUD',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'tenantId', type: 'string', format: 'uuid', required: true },
      { name: 'section', type: 'string', enum: ['worship', 'about', 'staff', 'location', 'news'], required: true },
      { name: 'data', type: 'object', note: '섹션별 구조(예배시간표·연혁·교역자[]·주소·소식[])' },
      { name: 'status', type: 'string', enum: ['draft', 'published'], required: true },
    ],
  },
  Subscription: {
    name: '구독', description: '테넌트 구독·과금. 해지·환불·연체 시 서비스 중단 정책',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'tenantId', type: 'string', format: 'uuid', required: true },
      { name: 'plan', type: 'string', enum: ['trial', 'basic', 'pro'], required: true },
      { name: 'monthlyFee', type: 'integer', example: 40000 },
      { name: 'billingDate', type: 'integer', example: 1, note: '매월 결제일' },
      { name: 'status', type: 'string', enum: ['trial', 'active', 'overdue', 'canceled'], required: true, note: 'overdue 30일+=suspended' },
    ],
  },
  Domain: {
    name: '커스텀 도메인', description: '교회별 독립 도메인(화이트라벨). DNS 확인',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'tenantId', type: 'string', format: 'uuid', required: true },
      { name: 'custom', type: 'string', example: 'eunsung.or.kr' },
      { name: 'dnsStatus', type: 'string', enum: ['pending', 'verified', 'failed'], required: true },
    ],
  },
  ReviewGate: {
    name: '이단심사', description: '교리 검증 게이트. 승인 전 노출 차단. ★법적 민감(종교 차별 소지)—기준·이의절차 필수',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'tenantId', type: 'string', format: 'uuid', required: true },
      { name: 'denomination', type: 'string', example: '장로회' },
      { name: 'status', type: 'string', enum: ['pending', 'approved', 'rejected', 'appealed'], required: true },
      { name: 'reviewerId', type: 'string', format: 'uuid' },
      { name: 'reason', type: 'string', note: '승인/반려 사유(이의신청 근거)' },
      { name: 'reviewedAt', type: 'string', format: 'date-time' },
    ],
  },
  Consent: {
    name: '동의(PIPA)', description: '개인정보 수집·이용 동의 원장. 목적별·철회 가능. 14세 미만=법정대리인',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'tenantId', type: 'string', format: 'uuid', required: true },
      { name: 'memberId', type: 'string', format: 'uuid', required: true },
      { name: 'purpose', type: 'string', enum: ['required', 'messaging', 'photo', 'sensitive', 'guardian'], required: true, note: 'guardian=법정대리인 동의' },
      { name: 'granted', type: 'boolean', required: true },
      { name: 'grantedAt', type: 'string', format: 'date-time' },
      { name: 'revokedAt', type: 'string', format: 'date-time' },
    ],
  },
  PrivacyRequest: {
    name: '개인정보 권리요청(PIPA)', description: '정보주체 권리행사(열람·정정·삭제·처리정지). 교인 제출 → 관리자 처리',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'tenantId', type: 'string', format: 'uuid', required: true },
      { name: 'memberId', type: 'string', format: 'uuid', required: true },
      { name: 'type', type: 'string', enum: ['access', 'correct', 'delete', 'stop'], required: true },
      { name: 'status', type: 'string', enum: ['pending', 'processing', 'done', 'rejected'], required: true },
      { name: 'requestedAt', type: 'string', format: 'date-time', required: true },
      { name: 'processedAt', type: 'string', format: 'date-time' },
    ],
  },
  Message: {
    name: '문자/푸시 발송', description: '대외 발송(문자지갑·푸시). ★수신동의·옵트아웃·야간발송 제한·멱등',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'tenantId', type: 'string', format: 'uuid', required: true },
      { name: 'channel', type: 'string', enum: ['sms', 'push'], required: true },
      { name: 'target', type: 'string', example: '전체 128 / 청년부 24', note: '수신거부자 자동 제외' },
      { name: 'content', type: 'string', required: true },
      { name: 'scheduledAt', type: 'string', format: 'date-time' },
      { name: 'status', type: 'string', enum: ['draft', 'scheduled', 'sending', 'sent', 'failed'], required: true },
      { name: 'sentCount', type: 'integer', example: 125, note: '실제 발송(옵트아웃 제외 후)' },
    ],
  },
  Notification: {
    name: '알림', description: '교인 인앱/푸시 알림(설교·공지·댓글). 수신설정·카테고리별 on/off',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'tenantId', type: 'string', format: 'uuid', required: true },
      { name: 'memberId', type: 'string', format: 'uuid', required: true },
      { name: 'type', type: 'string', enum: ['sermon', 'notice', 'comment', 'approval'], required: true },
      { name: 'title', type: 'string', required: true },
      { name: 'read', type: 'boolean', example: false },
      { name: 'createdAt', type: 'string', format: 'date-time', required: true },
    ],
  },
};
window.PDK_ENTITIES = window.PLANDECK_ENTITIES;
