window.PLANDECK_PRD = {
  version: '2.0.0',
  northStar: '하나의 플랫폼을 만들되, 교회와 교인에게는 각 교회의 독립적인 디지털 서비스처럼 보이게 한다. (PRD V2.0 §76)',
  background: '소규모 교회는 재정·인력난으로 자체 앱·홈페이지를 개별 개발(SI)하기 어렵고, 공용 입주형 교회앱은 교회 고유 브랜드를 담지 못한다. 훌메이트는 교회마다 시스템을 따로 개발하지 않고, 하나의 멀티테넌트 SaaS 플랫폼(단일 Backend·단일 Design System·단일 코드베이스) 위에서 각 교회가 교회명·로고·대표컬러·대표이미지·콘텐츠·도메인 등 설정값(Config)만으로 자기 교회만의 디지털 서비스를 운영하게 한다. 기본 제품은 Responsive Web + PWA(홈 화면 설치·Web Push)이며, 교인은 각 교회 독립 URL({slug}.hurmate.kr)로 들어와 "우리 교회 전용 앱"처럼 쓴다. Native App은 앱이 꼭 필요한 교회에만 추가 판매하는 Premium Add-on(차기). V1 구조에서 재기준화하되 코어(테넌트격리·인증·콘텐츠·개설승인·빌링·스토리지·디자인토큰)는 계승, V1 제외 모듈은 봉인(삭제 아닌 feature-flag OFF), 전무한 4대 공백(ChannelConfig/PwaConfig·Web Push·Notification Gateway·개설 Wizard)만 신규 구축한다.',
  goals: [
    '교회마다 홈페이지·앱을 따로 개발하지 않고, 하나의 플랫폼에서 설정값(Config)만으로 교회별 독립 Web/PWA를 발행',
    '교회·교인에게는 각 교회의 독립 디지털 서비스처럼 보이게 한다(화이트라벨 — 플랫폼 비가시성)',
    '제품 기본형 = Responsive Web + PWA + Web Push. Native App은 필요한 교회에만 Premium Add-on으로 분리 판매',
    '목회자가 관리자 콘솔에서 설교·주보·공지·회원·알림을 개발자 없이 직접 운영',
    '교회가 늘어도 코드가 아니라 Tenant와 Configuration만 늘어나는 구조 유지(운영 가능성 > 기능 추가)',
  ],
  users: [
    { role: '교인(성도)', jobStory: '우리 교회 URL/PWA로 들어와 교회 검색 없이 바로 가입하고, 홈·설교·주보·공지(+교회소개)를 보고 마이에서 내 정보·알림을 관리하며, 홈 화면에 "우리 교회 앱"처럼 설치해 알림(Web Push)을 받고 싶다' },
    { role: '방문자(새가족)', jobStory: '교회 공개홈에서 예배 시간·오시는 길·설교·분위기를 확인하고 싶다' },
    { role: '교회 관리자(목회자)', jobStory: '개설 Wizard로 교회를 오픈하고, 개발자 없이 설교·주보·공지·회원·알림을 관리하며 우리 교회 데이터만 안전하게 다루고 싶다' },
    { role: '플랫폼 운영자(HurMate Super Admin)', jobStory: '여러 교회(테넌트)를 하나의 콘솔에서 개설 승인·Tenant 생성·서비스 상태·요금제·결제·채널(PWA/App/Notification/Storage)까지 통합 관제하고 싶다' },
  ],
  scope: [
    '[면1·대표사이트 www] 서비스/기능 소개·WEB 상품·APP 상품·가격 안내·도입 절차·FAQ·로그인·교회 개설 신청·문의 (§23·61)',
    '[면2·교회 Web/PWA] 공개홈 5메뉴(HOME·교회소개·설교·주보·공지) + 교인 앱 5탭(홈·설교·주보·공지·마이) + 회원가입·로그인·Web Push, PC·Mobile 동일 반응형 (§28·61)',
    '[면3·교회 관리자 admin] Dashboard·교회 설정·공지·설교·주보·회원·알림·관리자(+앱/PWA·요금제·사용현황) — 본인 교회만(테넌트 스코프) (§37·61)',
    '[면4·슈퍼관리자 console] 교회 개설 승인·Tenant·서비스 상태·요금제·결제·회원·관리자·Notification·Storage·App 상태·운영 로그 (§45·61)',
    '교회 개설 종단연결(작업계획 9단계): 가입→개설 신청→요금제 선택→HurMate 승인→Tenant 자동생성→관리자 Wizard(8STEP)→오픈→교인 가입(church_id 자동)→알림 (§24·27·35)',
    'PWA: 교회별 manifest·아이콘·이름 동적 생성, 홈 화면 설치 유도(Android 프롬프트 / iOS 16.4+ 수동 안내) (§7·8)',
    '알림: Web Push 기본 채널 + Notification Gateway 추상화 + 구조화 Deep Link(type+content_id), 즉시/예약·전체회원 발송 (§9·39·40·41)',
    '데이터/채널: ChannelConfig(채널 on/off)·PwaConfig·AppConfig·PushSubscription·OnboardingApplication, 멀티테넌트 절대격리 (§51·53·54·55)',
    '화이트라벨: 교회별 변경 = 교회명·로고·대표색·대표이미지·도메인·PWA Icon·PWA Name만, 나머지는 단일 Design System 고정 (§57·75)',
    '1차 시장검증 버전: 3~5개 교회에 PC Web + Mobile Web + PWA + Web Push까지(Native 제외) (§64)',
  ],
  outOfScope: [
    'Native App 전체 — 기본 상품 아님, 선택형 Premium Add-on으로 차기(Phase6)·앱이 꼭 필요한 교회에만 (§62·65·72)',
    '"앱부터 개발" 금지 — 개발 순서 Backend→Admin→Web→PWA→Web Push→Native 강제 (§63)',
    '헌금 실 PG 결제 / 전자기부금영수증(세무) — 봉인(헌금·회계) (§60)',
    '교적(교구·구역·셀·직분·가족관계·세례·헌금·출석) 전체 — 회원은 이름·휴대전화·이메일·교회·가입상태만 (§34·60)',
    '출석 관리(QR/온라인) — 봉인 (§60)',
    '커뮤니티(나눔터)·댓글·채팅·UGC 모더레이션 — 봉인 (§60)',
    '아나바다(중고거래)·성도매장(쇼핑) — 봉인 (§60)',
    '교회학교(교육관리)·예약(reservation) — 봉인 (§60)',
    '라이브 방송 자체 호스팅 / 설교 자체 영상 저장 — 설교는 YouTube 링크만 (§31·60)',
    '광고·쇼핑·AI·복잡한 CRM·회계·복잡한 통계 — 봉인 (§60)',
    '알림 그룹/개별 타겟팅·알림톡(Kakao)·SMS — 향후(V2 MVP는 전체회원 Web Push만) (§39·40)',
    '교회별 UI 구조/레이아웃/메뉴 커스터마이즈 — 영구 금지(제작대행 아님, Template이 아니라 Design System) (§57·58)',
    '교회별 Backend/Admin/DB/Web 개발·App Source Fork — No-Fork 불변식 (§73)',
    'PIPA 개인정보 권리요청 화면 — V2 MVP admin 메뉴(§61)에서 제외(법적 필요 시 재도입 — J-게이트 G2)',
  ],
  successMetrics: [
    { metric: '관리자 콘텐츠 등록(§64-①)', target: '파일럿 교회가 설교·주보·공지를 실제로 등록' },
    { metric: '교인 이용(§64-②)', target: '교회 Web/PWA 교인 접속·열람 발생(파일럿 MAU)' },
    { metric: '홈 화면 PWA 설치(§64-③)', target: '교인 홈 화면 설치 유의미 발생(Android/iOS 16.4+)' },
    { metric: 'Push 허용(§64-④)', target: '알림 권한 허용률 확보' },
    { metric: 'Push 확인(§64-⑤)', target: 'Web Push open / Deep Link 이동 발생' },
    { metric: '유료 지불 의사 WTP(§64-⑥·G4)', target: '3~5개 교회 유료 LOI/선지불 의사(무료 대체재 대비 지불 이유 선검증)' },
  ],
  constraints: [
    '멀티테넌트 절대조건: 모든 데이터 tenant_id 귀속, 모든 API tenant 검증, A교회↔B교회 완전 격리(논리적 격리, 물리 분리 아님) (§54·55·74-2)',
    '디자인 자유도 제한: 교회별 변경은 로고·대표색·커버이미지·교회명(+도메인·PWA Icon/Name)만, Layout/Navigation/Component/Grid/Typography/PageStructure 고정 — Template 아니라 Design System (§57·58)',
    'No-Fork: 교회별 코드를 포크하지 않고 차이는 Configuration으로만 처리 (§73·74-3·74-4)',
    '개발 순서 강제: Backend→Admin→Web→PWA→Web Push→Native, "Native App부터 만드는 것 금지" (§63)',
    '콘텐츠 하드코딩 금지 — 앱/웹은 Tenant API로 데이터 조회(앱 업데이트 없이 콘텐츠 변경) (§17·74-13·74-14)',
    '교인 메뉴 5개 고정·교회별 변경 불가, PC·Mobile 동일 콘텐츠 구조 (§28)',
    'APP 상품을 BASIC SaaS 가격에 포함 금지(과금 분리 불변식) (§68)',
    '기능 추가 게이트: 다른 교회도 쓰는가/공통 모듈화 가능/운영비 적음/UX 안 해침/반복 요구 중 3+ YES → 백로그, 아니면 Custom 분리 (§59)',
    '운영 가능성이 기능 추가보다 우선(최상위 원칙) (§74-20)',
    '가역성: 봉인은 삭제가 아닌 feature-flag OFF, 손실성 마이그레이션(예: Theme 다색→단일색)은 down-migration·컬럼 백업 동반(작업계획)',
    '정직성: 미확보 콘텐츠(계좌·영상·연혁)는 "교회 확인 후 게재" placeholder(임의 기재 금지)',
  ],
  assumptions: [
    '조건 충족 PWA는 iOS/Android에서 Web Push 제공 가능 — iOS/iPadOS 16.4+는 홈 화면 설치 Web App의 Web Push를 공식 지원("Web은 푸시 불가" 전제 폐기) (§9)',
    '교인은 스마트폰(모바일) 중심, 관리자·운영자는 PC웹 중심',
    '설교 영상은 YouTube URL 연동(자체 호스팅 아님) (§31)',
    '교회별 독립 URL/PWA/App 진입 자체가 Tenant를 결정하므로 교인은 교회 검색이 필요 없다(church_id 자동 바인딩) (§35)',
    '대부분 교회는 Web+PWA로 충분하고, 앱이 꼭 필요한 교회만 Native App을 추가 구매한다 (§76)',
    'Native App 제공 시 교회가 자체 Apple/Google 개발자 계정을 보유하고 HurMate는 기술 운영자로 참여(차기) (§18·19)',
    'Church가 Tenant를 겸함(tenant_id = church.id)으로 V1 충분, 분리는 커스텀도메인·다채널 확장 시점에 결정(작업계획 O1)',
  ],
  dependencies: [
    'platform-db churchhub 스키마(멀티테넌트 — 앱레벨 격리 + 가능 시 DB RLS 이중 방어)',
    '화이트라벨 엔진: 테넌트 라우팅({slug}.hurmate.kr)·동적 PWA manifest·테마(브랜드) 주입',
    'Notification Gateway(공통 발송 모듈) + VAPID/web-push 라이브러리(Web Push)',
    'YouTube(설교 메타·임베드 재생)',
    '지도 API(§30 오시는 길) — 키리스 임베드 vs 카카오/구글 키(선행 게이트 G3)',
    '(차기·Native) FCM/APNs, 교회 소유 Apple Developer·Google Play 계정, CI/CD, App Store/Google Play 배포',
    '커스텀 도메인(Premium) DNS 확인 (§56)',
    '이메일 발송(개설 승인·초대 — 4→5 약한 고리 보강, 작업계획 Phase2)',
  ],
  releases: [
    { name: 'Phase 0 — 착수 전 게이트', scope: ['G1~G4 선행 결정(§57 완화범위·PII/보안·지도API·유료 WTP)', 'O1·O2·O4·O5 확정', 'docs 실측 재인벤토리·결정 로그 확정'], when: '코드 착수 전' },
    { name: 'Phase 1 — Core Platform(Backend)', scope: ['멀티테넌트 백본·인증·Church·권한·Super Admin 재정렬', 'ChannelConfig·billing_plan 신설', '제외 7모듈 feature-flag OFF + import 잔존 0', 'Theme 손실성 마이그레이션(down-migration·백업)', '개설 승인 시 ChannelConfig·PwaConfig 자동생성'], when: 'Phase0 통과 후' },
    { name: 'Phase 2 — Church Admin', scope: ['개설 Wizard 8STEP 상태기계', 'Admin(Dashboard·설정·공지·설교·주보·회원·알림·관리자)', '회원 모델 단순화(RBAC 유지)', 'PwaConfig 편집 골격', '승인 알림(이메일)'], when: 'Phase1 후' },
    { name: 'Phase 3 — Web(PC+Mobile 반응형)', scope: ['교회 공개홈+교인 Web 고정 5메뉴·단일 DS', '{slug}.hurmate.kr 라우팅·guard(교회검색·switchChurch 제거)', '대표사이트 개설 퍼널', '제외 화면 strip+아카이브'], when: 'Phase2 후' },
    { name: 'Phase 4 — PWA(교회별 독립 설치)', scope: ['PwaConfig 소비 manifest 동적 생성', '교회별 아이콘 파이프라인(192/512/maskable)', '설치 유도(교회명 문구·iOS16.4+ 분기)', 'Super Admin PWA 콘솔 최소뷰', 'SW·push 핸들러 설계'], when: 'Phase3 후' },
    { name: 'Phase 5 — Notification(Web Push) ★MVP 완성·1차 시장검증', scope: ['PushSubscription·VAPID·구독/해지 API·권한 UI', 'SW push/notificationclick·발송 워커', 'Notification Gateway(InApp+WebPush 어댑터, Native/Kakao/SMS 슬롯)', '구조화 Deep Link(type+content_id) 라우팅', '즉시/예약/전체회원 fan-out'], when: 'Phase4 후 — 1차 검증(3~5교회) 완성선' },
    { name: 'Phase 6 — Native App Factory(차기·Premium Add-on)', scope: ['AppConfig 실사용', 'One codebase + Tenant Config + Automated Build', 'FCM·APNs(Gateway Native 어댑터)', 'Android/iOS 빌드·서명·스토어·심사·배포', 'Super Admin App Console', '교회 소유 개발자계정 운영대행·CI/CD'], when: '1차 검증·유료 지불의사 확인 후' },
  ],
  // ── 비기능 요구사항(NFR) — 멀티테넌트/PWA/Push는 PRD V2.0 조항, 보안·접근성 수치는 V1 계승 엔지니어링 기준(PRD 미규정분 포함) ──
  nfr: {
    multitenant: ['모든 조회·쓰기 tenant_id 스코프 강제 + 모든 API tenant 검증', '앱레벨 격리 + 가능 시 DB RLS 이중 방어', '신규 엔티티 전부 TenantScopedEntity 상속을 CI 게이트로 검증 (§55·작업계획 D7)'],
    pwa: ['서비스워커·오프라인 캐싱·설치 유도·업데이트 알림·오프라인 fallback', 'iOS 16.4+ 홈 설치 Web App의 Web Push 지원(그 미만 제약 고지) (§9)'],
    webPush: ['VAPID·권한 요청 UX·수신동의 연계·야간 발송 제한', 'PushSubscription을 tenant+user 이중 스코프·멀티기기 다중 구독으로 설계(iOS 오배송 방지) (작업계획 D4)'],
    security: ['[계승] JWT·HTTPS 전용·민감정보 암호화(알고리즘은 G2 security-review에서 확정)·감사로그·교차테넌트 접근 기록 (§55)'],
    accessibility: ['[계승] WCAG 2.1 AA — 고령 교인 대상 본문 16px+·대비 4.5:1·터치 타깃 44px+·스크린리더 레이블'],
    performance: ['[계승] 주일 예배 트래픽 스파이크 대비·홈 응답 목표·CDN·이미지 최적화'],
    operability: ['운영 가능성 > 기능 추가(최상위 원칙)', '제외 모듈 import 잔존 0 grep 게이트(전 KEEP 모듈로 확장) (§74-20·작업계획 D6)'],
  },
  // ── 권한 모델(RBAC) — V2.0 단순화(교적·직분 체계 봉인) ──
  rbac: {
    roles: ['member(교인)', 'admin(교회 관리자·목회자)', 'super(플랫폼 운영자)'],
    note: '회원은 이름·휴대전화·이메일·교회·가입상태만 보유(교적·직분 체계 봉인). 직분 기반 세부 권한 위임은 교적 재개 시 복원. 교회 관리자는 본인 교회(tenant)만, 슈퍼 운영자만 교차테넌트(모든 접근 감사로그).',
    matrix: [
      { who: 'member', can: '우리 교회 Web/PWA 열람·회원가입·알림 수신설정(church_id 자동 바인딩)' },
      { who: 'admin', can: '본인 교회 설정·설교·주보·공지·회원 조회/승인·알림 발송·앱/PWA·요금제/사용현황(테넌트 스코프)' },
      { who: 'super', can: '교회 개설 승인·Tenant/채널(ChannelConfig)·서비스 상태·요금제·결제·운영 로그(교차테넌트 — 전 접근 감사)' },
    ],
  },
  // ── 멀티테넌트 격리 계약(§54·55) ──
  tenancy: {
    isolation: '모든 데이터 tenant_id 귀속 + 모든 API tenant 검증 → A교회↔B교회 완전 격리(논리적 격리, 물리 분리 아님). 앱레벨 필터 + 가능 시 DB RLS 이중 방어.',
    identification: '교회별 독립 URL({slug}.hurmate.kr)/PWA/App 진입이 Tenant를 결정 → 교인 회원가입 시 교회 검색 없이 church_id 자동 바인딩 (§35).',
    channel: 'ChannelConfig로 테넌트별 채널(web/pwa/ios/android/web_push/native_push) on/off 제어 (§51).',
    crossTenant: '슈퍼관리자만 교차테넌트 접근 가능, 모든 접근은 감사로그 기록.',
    identity: 'Church가 Tenant를 겸함(tenant_id = church.id). 2계층 분리는 커스텀도메인·다채널 확장 시점에 결정(작업계획 O1).',
  },
  // ── 대체재·지불의사(WTP) — 전략 하방 방어 ──
  alternatives: {
    competitors: [
      { name: '네이버 밴드', cost: '무료', gap: '교회 전용 아님·독립 브랜드 없음·설교/주보/공지 구조 없음·광고' },
      { name: '카카오톡 채널', cost: '무료', gap: '공지 일방향·교회 Web/PWA/독립 앱 없음·브랜드 약함' },
      { name: '유튜브', cost: '무료', gap: '설교 송출만·공개홈/관리/알림/멤버십 전무' },
      { name: '공용 입주형 교회앱', cost: '유료', gap: '교회 고유 브랜드 없음(공용 틀)·독립 도메인/PWA 없음·커스터마이즈 제한' },
    ],
    differentiation: ['교회별 독립 Web + PWA(화이트라벨 — 우리 교회 전용 서비스처럼)', 'Web Push 기본 내장(iOS 16.4+ 포함)', '개설 Wizard로 개발자 없이 발행·운영', '필요한 교회만 Native App Premium Add-on'],
    wtp: '가격은 상품 구조(WEB vs APP)만 확정, 금액은 시장검증 후 확정(§66 — 미확정). (참고·작업계획) WTP 월 3~5만 가설은 J-게이트 G4 선검증 대상 — 무료 대체재(밴드·유튜브·카카오채널) 대비 지불 이유를 3~5교회 유료 LOI/선지불로 확인.',
    risk: '무료 대체재 대비 WTP가 핵심 하방 → Phase1 착수 전 유료 지불의사 확보(G4)로 비대칭 하방 닫기. 대규모 투입 전 선검증 필수.',
  },
  requirements: [
    { reqId: 'REQ-001', text: '방문자는 대표사이트에서 서비스/기능 소개·WEB 상품·APP 상품·가격 안내·도입 절차·FAQ를 보고 교회 개설을 신청한다 (§22·23)', surfaces: ['landing'] },
    { reqId: 'REQ-002', text: '신청자는 회원가입→교회 정보(교회명·대표자·담당자·전화·이메일·주소·규모·희망도메인) 입력→요금제 선택으로 개설을 신청한다 (§24·25)', surfaces: ['landing'] },
    { reqId: 'REQ-003', text: '플랫폼 운영자는 개설 신청을 검토·승인하면 시스템이 Tenant·Church·Admin User·Domain·Storage·Theme·PWA Manifest·Notification Setting을 자동 생성한다 (§24·26)', surfaces: ['super'] },
    { reqId: 'REQ-004', text: '교회 관리자는 최초 설정 Wizard(교회명→로고→대표컬러→대표이미지→담임목사·주소·연락처·소개→예배시간→서비스 확인→OPEN) 8STEP을 완주해 서비스를 공개한다 (§27)', surfaces: ['admin'] },
    { reqId: 'REQ-005', text: '방문자/교인은 교회별 URL({slug}.hurmate.kr)로 접속하면 교회 검색 없이 Tenant가 확정되고 교회 공개홈(로고·대표이미지·예배안내·최근공지·최근설교·이번주 주보)을 본다 (§29·35)', surfaces: ['site', 'app'] },
    { reqId: 'REQ-006', text: '교인 대면 화면은 고정 메뉴로 제공되며 교회별 변경 불가, PC·Mobile 동일 반응형이다 — 공개홈(방문자)은 HOME·교회소개·설교·주보·공지 5메뉴, 로그인 교인 앱은 홈·설교·주보·공지·마이 5탭(교회소개는 홈 내 링크로 공개홈 교회소개 연결, 마이는 내 정보·알림설정·로그아웃) (§28)', surfaces: ['site', 'app'] },
    { reqId: 'REQ-007', text: '관리자는 설교(제목·설교자·날짜·성경본문·설명·YouTube URL·썸네일)를 등록하고 교인은 재생한다(자체 영상 저장 없음) (§31)', surfaces: ['admin', 'site', 'app'] },
    { reqId: 'REQ-008', text: '관리자는 주보(PDF/이미지)를 발행하고 교인은 열람한다 (§32)', surfaces: ['admin', 'site', 'app'] },
    { reqId: 'REQ-009', text: '관리자는 공지(제목·본문·이미지·첨부·게시일·중요공지·상단고정·알림 발송 여부)를 작성하고 교인은 확인한다 (§33)', surfaces: ['admin', 'site', 'app'] },
    { reqId: 'REQ-010', text: '교회소개(교회명·로고·담임목사·소개·주소·연락처·예배시간·지도·오시는 길)를 노출한다 (§30)', surfaces: ['site', 'app'] },
    { reqId: 'REQ-011', text: '교회 URL/PWA/App 진입 사용자는 교회 검색 없이 회원가입하면 church_id가 자동 바인딩되고 가입은 승인대기(가입상태)로 처리된다 (§35)', surfaces: ['site', 'app'] },
    { reqId: 'REQ-012', text: '회원은 이름·휴대전화·이메일·교회·가입상태만 보유(교적 미사용)하고, 관리자는 회원을 조회·승인한다 (§34)', surfaces: ['admin', 'app'] },
    { reqId: 'REQ-013', text: '교인은 모바일 웹에서 "교회 앱처럼 이용하세요" 안내로 홈 화면에 설치하면 교회 로고+교회명 아이콘으로 설치된다(Android 설치 프롬프트 / iOS 수동 안내) (§7·8)', surfaces: ['site', 'app'] },
    { reqId: 'REQ-014', text: '교회 기본정보에서 PWA 설정(이름·Short Name·아이콘·테마컬러·start_url·manifest)을 자동 생성하고 관리자가 보정한다 (§42·53)', surfaces: ['admin', 'super'] },
    { reqId: 'REQ-015', text: '교인은 알림 권한을 허용하고(iOS 16.4+ 홈 설치 PWA 포함) 관리자 발송 시 Web Push를 수신한다 (§9)', surfaces: ['app', 'site', 'admin'] },
    { reqId: 'REQ-016', text: '관리자 알림 발송은 Notification Gateway를 경유(MVP=Web Push, 향후 Native/Kakao/SMS)하며 즉시/예약·전체회원 발송을 지원한다 (§39·40)', surfaces: ['admin'] },
    { reqId: 'REQ-017', text: '알림 클릭 시 type+content_id로 해당 콘텐츠(예: 이번 주 주보)로 바로 이동한다(Deep Link) (§41)', surfaces: ['app', 'site'] },
    { reqId: 'REQ-018', text: '교회 관리자는 admin.hurmate.kr 로그인 시 본인 교회 데이터만 보고(테넌트 스코프) Dashboard(회원수·최근공지/설교/주보·알림 발송 수·스토리지 사용량)·설정·공지·설교·주보·회원·알림·관리자·앱/PWA·요금제·사용현황을 운영한다 (§36·37·38)', surfaces: ['admin'] },
    { reqId: 'REQ-019', text: '교회별 변경은 로고·대표색·커버이미지·교회명(+도메인·PWA Icon/Name)만 반영되고 Layout/Navigation/Grid/Typography는 단일 Design System으로 고정된다 (§57·75)', surfaces: ['admin', 'site', 'app'] },
    { reqId: 'REQ-020', text: '운영자는 전체 교회 목록(교회명·Tenant ID·도메인·가입일·요금제·회원수·관리자수·PWA·App·서비스 상태·결제 상태)과 서비스 상태 라이프사이클(신청→검토→개설→활성→일시정지→해지)·요금제·결제를 관리한다 (§45·46·47)', surfaces: ['super'] },
    { reqId: 'REQ-021', text: '테넌트별 채널(web/pwa/ios/android/web_push/native_push) on/off를 ChannelConfig로 제어한다 (§51)', surfaces: ['super', 'admin'] },
    { reqId: 'REQ-022', text: '모든 데이터는 tenant_id에 귀속되고 모든 API에서 tenant 검증을 실시해 A교회↔B교회 접근을 차단한다 (§54·55)', surfaces: ['super', 'admin', 'app', 'site'] },
    { reqId: 'REQ-023', text: '기본 도메인은 {slug}.hurmate.kr이며 Premium 옵션으로 커스텀 도메인을 연결한다 (§56)', surfaces: ['super', 'admin'] },
    { reqId: 'REQ-024', text: '운영자/관리자는 WEB(초기 등록비+월 이용료)과 APP(구축비+스토어 등록·관리비+연간 유지비) 상품 구조로 구독·과금하며 APP은 BASIC에 포함하지 않는다. 금액은 시장검증 후 확정 (§66·67·68)', surfaces: ['landing', 'super', 'admin'] },
    { reqId: 'REQ-025', text: '[차기] 앱이 꼭 필요한 교회에 한하여 교회별 White Label Native App(One codebase + Tenant Config + Automated Build, Native Push·Deep Link, 교회 소유 개발자계정 운영대행)을 Premium Add-on으로 제공한다 (§13·14·65·72)', surfaces: ['admin', 'super'] },
    { reqId: 'REQ-SEAL', text: '[봉인·V1 제외] 헌금·전자기부금영수증·교적·출석·커뮤니티·아나바다·성도매장·교회학교·검색·PIPA 권리요청·이단심사 등 V1 기능군은 삭제가 아닌 feature-flag OFF로 봉인(향후 Add-on 자산). 아카이브 화면으로 보존·검토용 (§60·작업계획 §3.2)', surfaces: ['app', 'site', 'admin', 'super'] },
  ],
  workflows: [
    { name: '대표사이트 방문→교회 개설 신청', steps: ['대표사이트 접속(www.hurmate.kr)', '가격 안내·WEB/APP 상품 확인', '회원가입', '교회 정보 입력', '요금제 선택', '개설 신청 제출'] },
    { name: '개설 승인→Tenant 자동 프로비저닝', steps: ['운영자 신규 신청 검토', '승인(검토→개설)', 'Tenant·Church·Admin User 자동 생성', 'Domain·Storage·Theme·PWA Manifest·Notification Setting 생성', '관리자 계정 발급·초대 알림'] },
    { name: '교회 관리자 최초 Wizard→오픈', steps: ['로고·대표컬러·대표이미지 설정', '담임목사·주소·연락처·소개 입력', '예배시간 입력', '서비스 확인', 'OPEN(status=활성)'] },
    { name: '교인 진입→가입(교회검색 없음)', steps: ['교회 URL/PWA 진입', 'Tenant 자동 확정', '회원가입', 'church_id 자동 바인딩', '승인대기'] },
    { name: 'PWA 설치(교회 전용 앱처럼)', steps: ['모바일 웹 접속', '"우리 교회 앱처럼 이용하세요" 설치 안내', '홈 화면에 설치(Android 프롬프트 / iOS 수동)', '교회 로고+교회명 아이콘 생성', '아이콘으로 교회 서비스 실행'] },
    { name: '공지 작성→Web Push→교인 확인', steps: ['관리자 공지 작성(알림 발송 ON)', 'Notification Gateway 경유', 'Web Push 발송(즉시/예약)', '교인 알림 수신', 'Deep Link로 공지 이동'] },
    { name: '슈퍼관리자 통합 운영', steps: ['전체 교회 목록 조회', '서비스 상태 전이(활성↔일시정지→해지)', '요금제·결제 관리', '서비스 콘솔(PWA·App·Notification·Storage)'] },
  ],
  resolvedDecisions: [
    '플랫폼 = Multi-Tenant SaaS, 데이터는 논리적으로 격리(물리 분리 아님) (§75·74-2)',
    '기본 서비스 = Responsive Web + PWA + Web Push (§75)',
    'Native App = 선택형 Premium Add-on, Phase6 차기·앱 필요 교회에만 (§65·75)',
    '브랜딩 변경 가능 요소 = 교회명·교회 로고·대표색·대표 이미지·도메인·PWA Icon·PWA Name (§75)',
    '관리자 2종 = Church Admin(admin.hurmate.kr) + HurMate Super Admin(console.hurmate.kr) (§36·44·75)',
    'MVP 기능 6개 = 교회소개·설교·주보·공지·회원·알림 (§75)',
    '앱 구조 = One Codebase + Tenant Config + Automated Build, No-Fork (§73·75)',
    '회원가입 시 교회 검색 제거 — 진입 채널이 Tenant를 결정해 church_id 자동 바인딩 (§35)',
    '교인 메뉴 5개 고정·변경 불가, 디자인은 4요소만 교회별 변경(단일 Design System) (§28·57)',
    '개발 순서 = Backend→Admin→Web→PWA→Web Push→Native, 앱 선개발 금지 (§63)',
    '1차 시장검증 = 3~5개 교회에 Web+PWA+Web Push까지(Native 제외) (§64)',
    '서비스 상태 표준 enum 6단계 = 신청·검토·개설·활성·일시정지·해지 (§47)',
    '알림 = Notification Gateway 공통 모듈, MVP 채널 Web Push(+설계상 Native Push), 향후 Kakao/SMS (§39)',
    '봉인 = 삭제 아닌 feature-flag OFF(향후 Add-on 자산), 손실성 마이그레이션은 down-migration·백업 동반(작업계획)',
    '브랜드 도메인 hurmate.kr 통일: www(대표)·{slug}(교회)·admin·console (작업계획)',
    '재기준화(권장안 A): 코어 KEEP + V1 제외 모듈 봉인 + 4대 공백(ChannelConfig/PwaConfig·Web Push·Notification Gateway·개설 Wizard) BUILD (작업계획)',
    'Church가 Tenant 겸함 유지로 V1 충분(tenant_id=church.id), 분리는 O1 시점 (작업계획)',
    '— 가격 구조(§66~68) —',
    '가격 = 상품 구조(WEB vs APP)만 처음부터 분리, 정확한 금액은 시장검증 후 확정(미확정) (§66)',
    'HurMate WEB = 초기 등록비 + 월 이용료. 월 SaaS 포함 범위 = Web / Mobile / PWA / Web Push / Admin (§66·67)',
    'HurMate APP = WEB + APP 구축비 + App Store 등록·관리비 + 월/연 유지비. APP은 BASIC SaaS 가격에 포함 금지(교회별 Bundle ID·서명·심사·Push 인증 등 반복 운영비) (§66·68)',
    '커스텀 도메인 = Premium 유료 옵션 (§56). 추천 과금은 예시일 뿐 확정 가격 아님 (§67)',
  ],
  openQuestions: [
    'G1 §57 완화 범위 — "교회 템플릿 제공"의 의미: (A) 브랜드·콘텐츠·메뉴 On/Off로 교회마다 달라 보이기(§57 준수·지금 설계) vs (B) 교회가 레이아웃 시안 자체 선택(§57 완화 필요·보류). 권장=A, B는 J 승인 게이트',
    'G2 PII·보안 — AppUser의 ci(본인확인 민감정보)·gender·birthDate 수집/보관: 수집 중단 vs 암호화+근거. security-review High=0 + 개인정보처리방침·DPA 대조',
    'G3 외부 의존(지도 API) — §30 오시는 길: 키리스 임베드 vs 카카오/구글 키 발급(키·비용·명의)',
    'G4 유료 WTP 선검증 — Phase1 착수 전 3~5교회 유료 LOI/선지불 의사 확보(무료 대체재 대비 지불 이유)',
    'O1 Tenant/Church 2계층 — 겸용 유지(권장) vs 지금 분리(커스텀도메인·다채널 확장 시점)',
    'O4 설치 대상 앱 — member 교인앱 중심(권장) vs home 공개홈 vs 통합 / O5 단일 고정 시안 — welcome(환영형·권장·고령 배려) vs demo',
    '이단심사(교리 검증 게이트) V2 존치 여부 — PRD V2.0 원문 미언급, 현재는 개설 "승인(§24)=검토(§47)"로 대체. 별도 교리 게이트를 유지할지 J 확인',
    'PIPA 개인정보 권리요청 화면 — V2 MVP admin 메뉴(§61)에서 빠졌으나 법적 의무와 상충 가능 → 봉인/최소유지 판단(G2 연계)',
  ],
  // 개발 착수 전 기획자(J) 결재 게이트 — 규제·결제·대외발송·전략 선결
  jGate: [
    'G1 §57 완화 범위(교회 템플릿 제공 의미) 승인 — 레이아웃 시안 선택(B축)은 J 승인 전 금지',
    'G2 PIPA·PII — ci/gender/birthDate·민감정보 처리 법무 검토 + security-review(High=0)',
    'G3 지도 API — 키·비용·명의 결정',
    'G4 유료 WTP — 3~5교회 LOI/선지불 선검증(대규모 투입 전 비대칭 하방 닫기)',
    '헌금 계좌 안내/향후 PG — 유사수신·전자금융 규제 경계(실결제는 봉인으로 현 단계 회피)',
    '전자기부금영수증(세무)·대량 발송(수신동의·옵트아웃·야간 제한) — 봉인/차기 재개 시 사전 합의',
    '(차기 Native) Apple/Google 화이트라벨 앱 정책·대량 등록 반복 콘텐츠 리스크 — 무차별 판매 금지, 교회 소유 개발자계정 (§18·19·20)',
  ],
};
window.PDK_PRD = window.PLANDECK_PRD;
