window.PLANDECK_PRD = {
  version: '0.1.0',
  background: '소규모 교회(예장통합 100명 이하 72%)는 재정·인력난으로 자체 앱·홈페이지를 갖기 어렵고, 기존 공용 입주형 앱은 교회 고유 브랜드를 담지 못한다. 훌메이트는 한 코드베이스(화이트라벨 멀티테넌트)로 교회마다 독립 브랜드의 교인앱·공개홈·관리자콘솔을 30분 내 발행하고 유지비를 최소화한다. 은성교회를 1호 파일럿으로 검증한다.',
  goals: [
    '교회별 독립 브랜드 앱(교인앱·공개홈)을 코드 복제 없이 설정값만으로 발행',
    '목회자가 콘솔에서 설교·공지·성도를 직접 관리(개발자 없이 운영)',
    '개인정보보호(PIPA)를 기본 내장 — "가입만 해도 법 준수"',
    '파일럿(은성) 기준 공개홈·교인앱 운영 품질 달성',
  ],
  users: [
    { role: '교인(성도)', jobStory: '우리 교회 앱에서 설교를 보고 공지·헌금안내를 확인하고 싶다' },
    { role: '목회자/관리자', jobStory: '개발자 없이 설교·성도·공지를 직접 관리하고 현황을 보고 싶다' },
    { role: '방문자(새가족)', jobStory: '교회 공개 홈에서 예배 시간·오시는 길·분위기를 알고 싶다' },
    { role: '플랫폼 운영자', jobStory: '여러 교회(테넌트)를 한 플랫폼에서 안전하게 운영·분리하고 싶다' },
  ],
  scope: [
    '교인앱(모바일 PWA): 홈·설교·헌금안내·마이',
    '공개홈(모바일): 환영형 홈·예배안내',
    '관리자콘솔(PC웹): 대시보드·성도관리(교적)',
    '화이트라벨: 테넌트별 브랜드(색·로고)·기능 On/Off·공개홈 템플릿',
  ],
  outOfScope: [
    '헌금 실 PG 결제(파일럿=안내전용)',
    'SMS 발송(푸시로 대체)',
    '교적 프론트(은성 파일럿은 교적 OFF — 운영자만)',
  ],
  successMetrics: [
    { metric: '파일럿 공개홈·교인앱 운영 품질', target: '은성 실데이터로 실렌더 합격' },
    { metric: 'SOM(3년)', target: '1,000교회 · 구독 ARR 4.8억(목표)' },
    { metric: '발행 소요', target: '교회 1곳 30분 내 브랜드 앱 발행' },
  ],
  constraints: [
    '멀티테넌트 격리 — 모든 조회·쓰기는 교회(tenant) 스코프 강제',
    'PIPA 내장 — 민감정보(주민번호) service_role 전용·암호화·마스킹, 동의 원장',
    '정직성 — 미확보 콘텐츠(계좌·영상·연혁)는 "교회 확인 후 게재" placeholder(임의기재 금지)',
  ],
  assumptions: [
    '교인은 스마트폰(모바일) 중심, 관리자는 PC웹 중심',
    '설교 영상은 유튜브 URL 연동(자체 호스팅 아님)',
  ],
  dependencies: [
    'platform-db churchhub 스키마(멀티테넌트)',
    '화이트라벨 엔진(테넌트 라우팅·동적 manifest·테마 주입)',
  ],
  releases: [
    { name: 'Pilot(은성 1호)', scope: ['공개홈', '교인앱', '관리자 대시보드·성도관리'], when: '파일럿' },
    { name: 'Phase 0 MVP', scope: ['출석', '전자기부금영수증', '문자지갑', 'PIPA'], when: '파일럿 후' },
  ],
  requirements: [
    { reqId: 'REQ-001', text: '교인은 앱 홈에서 이번 주 설교·공지·바로가기를 본다', surfaces: ['app'] },
    { reqId: 'REQ-002', text: '교인은 설교를 재생하고, 관리자는 설교를 등록·라이브 토글한다', surfaces: ['app', 'admin'] },
    { reqId: 'REQ-003', text: '교인은 헌금 종류·계좌 안내를 확인한다(안내전용)', surfaces: ['app'] },
    { reqId: 'REQ-004', text: '교인은 로그인·마이에서 내 정보를 보고, 가입은 승인대기로 처리된다', surfaces: ['app'] },
    { reqId: 'REQ-005', text: '방문자/교인은 공개 환영형 홈·공개 설교를 본다', surfaces: ['site'] },
    { reqId: 'REQ-006', text: '방문자는 예배 시간·부서·오시는 길을 확인한다', surfaces: ['site'] },
    { reqId: 'REQ-007', text: '관리자는 대시보드에서 성도·출석·헌금 현황을 본다', surfaces: ['admin'] },
    { reqId: 'REQ-008', text: '관리자는 성도(교적)를 카드·직분·이력으로 관리한다', surfaces: ['admin'] },
    { reqId: 'REQ-009', text: '관리자는 예배별 출석을 체크하고 장기결석을 자동 감지한다', surfaces: ['admin'] },
    { reqId: 'REQ-010', text: '관리자는 헌금을 집계하고 전자기부금영수증을 발급한다(PIPA·세무)', surfaces: ['admin'] },
    { reqId: 'REQ-011', text: '교인은 커뮤니티(나눔터)에서 기도제목·간증을 나눈다', surfaces: ['app'] },
    { reqId: 'REQ-012', text: '교인은 아나바다(중고나눔)·성도매장을 이용한다', surfaces: ['app'] },
    { reqId: 'REQ-013', text: '교인은 교회학교 부서별 공지·일정을 본다', surfaces: ['app'] },
    { reqId: 'REQ-014', text: '교인은 주간 주보를 열람한다', surfaces: ['app'] },
    { reqId: 'REQ-015', text: '방문자는 교회 소개·섬기는 사람들·소식을 본다', surfaces: ['site'] },
    { reqId: 'REQ-016', text: '방문자는 새가족 안내를 보고 동의 기반으로 등록한다(PIPA)', surfaces: ['site'] },
    { reqId: 'REQ-017', text: '관리자는 공개홈 템플릿·브랜드(색·로고)를 설정한다(화이트라벨)', surfaces: ['admin'] },
    { reqId: 'REQ-018', text: '플랫폼 운영자는 교회(테넌트)를 발행·구독·심사 관리한다', surfaces: ['super'] },
    { reqId: 'REQ-019', text: '교인은 문자/푸시 알림을 받고, 관리자는 문자지갑을 관리한다', surfaces: ['app', 'admin'] },
    { reqId: 'REQ-020', text: '교인·관리자는 PIPA 동의 원장·개인정보 권리요청을 처리한다', surfaces: ['app', 'admin'] },
  ],
  workflows: [
    { name: '교인 설교 시청', steps: ['앱 홈', '설교 목록', '헌금 안내'] },
    { name: '방문자 공개홈', steps: ['공개 환영형 홈', '예배 안내', '오시는 길'] },
    { name: '관리자 운영', steps: ['관리자 대시보드', '성도관리', '출석 관리'] },
    { name: '설교 발행', steps: ['설교 관리', '교인앱 홈', '설교'] },
    { name: '화이트라벨 발행', steps: ['테넌트 관리', '홈페이지 설정', '공개 환영형 홈'] },
  ],
  openQuestions: [
    '요금(월 3~5만) 최종 확정 — 애드온 단가 정합',
    '실 푸시 인프라·PG 실연동 시점(안내전용 → 실결제)',
  ],
};
window.PDK_PRD = window.PLANDECK_PRD;
