/* 도담(DODAM) 데이터 모델 v2.0.0 — 실서비스 Supabase `dodam` 스키마 기준(3앱 공유 단일 진실원).
 * 🔒 = PIPA 민감/건강정보(자녀 장애·중증도·감각, 성범죄경력 결과, 연락처, 결제, 셀프체크 응답, 안전사건).
 * 권한: Profile.role(parent/partner/admin) + Partner.kind(공급 3역할) + AdminUser.permissions(콘솔 RBAC 매트릭스). */
window.PLANDECK_ENTITIES = {
  Profile: {
    name: '사용자(프로필)', description: '부모·파트너·관리자 공통 계정. 민감 연락처 포함, 닉네임 익명활동 지원',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true, note: 'auth FK' },
      { name: 'role', type: 'string', enum: ['parent', 'partner', 'admin'], required: true, example: 'parent' },
      { name: 'name', type: 'string', required: true, example: '김보호' },
      { name: 'phone', type: 'string', required: false, note: '🔒 민감 — 마스킹·동의', example: '010-••••-1234' },
      { name: 'nickname', type: 'string', example: '도담맘', note: '커뮤니티 익명 활동명' },
      { name: 'region', type: 'string', example: '고양시 일산동구' },
      { name: 'regionId', type: 'string', format: 'uuid', note: 'regions FK' },
      { name: 'publicProfile', type: 'boolean', example: false, note: '공개 프로필 노출 여부' },
      { name: 'grade', type: 'string', enum: ['새싹', '실버', '골드'], note: '부모 등급(포인트 기반)' },
      { name: 'status', type: 'string', enum: ['active', 'suspended', 'deleted'], required: true },
    ],
  },
  Child: {
    name: '아동(자녀)', description: '🔒 발달장애 아동 — 건강정보. 전면 선택입력·기본 비공개·항목별 공개범위·동의 게이트',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'parentId', type: 'string', format: 'uuid', required: true, note: 'Profile FK' },
      { name: 'name', type: 'string', example: '김도담' },
      { name: 'birthYear', type: 'integer', note: '🔒 공개 시 ageBand(구간)로 비식별', example: 2018 },
      { name: 'disabilityType', type: 'string', enum: ['청각', '시각', '지적', '발달', '신체', '중복', '기타'], note: '🔒 건강정보 — 공개 시 표준카테고리 de-identify' },
      { name: 'severity', type: 'string', enum: ['경증', '중등도', '중증'], note: '🔒 중증도' },
      { name: 'registrationStatus', type: 'string', enum: ['registered', 'suspected', 'none', 'undisclosed'], note: '등록·의심·해당없음·비공개' },
      { name: 'sensoryProfile', type: 'object', note: '🔒 감각 프로파일(소음·빛·촉각 민감 등)' },
      { name: 'need', type: 'array', note: '필요 배려', example: ['조용한 공간', '대기 최소화'] },
      { name: 'visibility', type: 'object', required: true, note: '항목별 공개범위(private/group/public) — 기본 전부 private', example: { disabilityType: 'private' } },
      { name: 'sensitiveConsent', type: 'boolean', required: true, note: '🔒 민감정보 처리 별도 동의(없으면 write 거부)' },
      { name: 'guardianConsent', type: 'boolean', required: true, note: '만 14세 미만 법정대리인 동의(PIPA)' },
    ],
  },
  Partner: {
    name: '파트너(공급자)', description: '공급 3역할 — 돌보미(유급)·앰배서더(무급)·매장파트너. 검증·등급·상태',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'profileId', type: 'string', format: 'uuid', required: true, note: 'Profile FK · unique(profileId,kind)' },
      { name: 'kind', type: 'string', enum: ['caregiver', 'ambassador', 'merchant'], required: true, note: '돌보미/앰배서더/매장파트너' },
      { name: 'region', type: 'string', example: '파주시 운정동' },
      { name: 'hourlyFee', type: 'integer', note: '시급(돌보미만)', example: 15000 },
      { name: 'rating', type: 'number', example: 4.9 },
      { name: 'reviewsCount', type: 'integer', example: 24 },
      { name: 'status', type: 'string', enum: ['onboarding', 'pending_review', 'approved', 'rejected', 'suspended'], required: true },
      { name: 'badge', type: 'string', note: '등급 뱃지(돌보미 브론즈/실버/골드 등)' },
    ],
  },
  PartnerOnboarding: {
    name: '파트너 검증(온보딩)', description: '🔒 공급자 신원검증 단일 레코드 — 성범죄경력·보험·자격·서류·교육 4게이트. 서류 파일 미저장(attestation만)',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'partnerId', type: 'string', format: 'uuid', required: true, note: '1:1' },
      { name: 'sexOffenseConsent', type: 'boolean', note: '🔒 아청법 성범죄경력 조회 동의' },
      { name: 'sexOffenseStatus', type: 'string', enum: ['pending', 'requested', 'verified', 'rejected'], note: '🔒 결과 사실만 — 원본 미저장' },
      { name: 'insurance', type: 'object', note: '배상책임보험(대인1억/대물1천) — 참조번호·만료일' },
      { name: 'insuranceStatus', type: 'string', enum: ['pending', 'verified', 'expired'] },
      { name: 'trainingStatus', type: 'string', enum: ['pending', 'completed'], note: '안전교육 4모듈+퀴즈' },
      { name: 'documents', type: 'object', note: '서류 attestation만(storage:none — 파일 미저장): 신분증·자격·경력·건강진단서 attested 키' },
      { name: 'reviewStatus', type: 'string', enum: ['pending_review', 'approved', 'rejected'], required: true },
      { name: 'reviewerId', type: 'string', format: 'uuid', note: 'AdminUser FK' },
      { name: 'reviewNotes', type: 'string', note: '반려 사유(필수)' },
    ],
  },
  Store: {
    name: '안심 매장/장소', description: '발달장애 친화 검증 장소. 6축 접근성·안심등급·적합유형·출처. 미입력 접근성=null 명시',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'name', type: 'string', required: true, example: '숲속 감각친화 카페' },
      { name: 'category', type: 'string', example: '카페', note: '병원·의원은 평가지표 숨김' },
      { name: 'region', type: 'string', example: '고양시 일산서구' },
      { name: 'regionId', type: 'string', format: 'uuid' },
      { name: 'address', type: 'string' },
      { name: 'lat', type: 'number', note: '지도 API 응답 영속저장 금지 — 좌표만 자체보관' },
      { name: 'lng', type: 'number' },
      { name: 'grade', type: 'string', enum: ['Bronze', 'Silver', 'Gold'], note: '안심 등급' },
      { name: 'status', type: 'string', enum: ['draft', 'pending', 'approved', 'rejected', 'suspended'], required: true },
      { name: 'accessibility', type: 'object', note: '6축: 감각·직원응대·공간·화장실·물리·식이(미입력=null)' },
      { name: 'scores', type: 'object', note: '5L: 이동·감각·직원·환영·어울림' },
      { name: 'suitableTypes', type: 'array', note: '적합 장애유형 태그' },
      { name: 'verified', type: 'boolean', required: true },
      { name: 'source', type: 'string', enum: ['self', 'parent_verified', 'public_data', 'partner', 'field_report', 'admin'], note: '장소 출처' },
      { name: 'ownerProfileId', type: 'string', format: 'uuid', note: '매장파트너 claim 시' },
    ],
  },
  StoreCertApplication: {
    name: '매장 인증 심사', description: '6축 접근성 자기평가·현장채점·확정등급 심사',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'storeId', type: 'string', format: 'uuid', required: true },
      { name: 'appliedGrade', type: 'string', enum: ['Bronze', 'Silver', 'Gold'] },
      { name: 'selfScores', type: 'object' },
      { name: 'fieldScores', type: 'object', note: '운영자 현장채점 1~5' },
      { name: 'status', type: 'string', enum: ['submitted', 'under_review', 'field_scheduled', 'passed', 'conditional', 'failed'], required: true },
      { name: 'reviewerId', type: 'string', format: 'uuid' },
    ],
  },
  StorePhoto: {
    name: '매장 사진', description: '저작권 — 직접촬영/업로더 동의/출처명시 중 하나. consent 미체크 제출 차단',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'storeId', type: 'string', format: 'uuid', required: true },
      { name: 'url', type: 'string' },
      { name: 'uploaderId', type: 'string', format: 'uuid' },
      { name: 'consent', type: 'boolean', required: true, note: '필수 true — 미체크 차단' },
      { name: 'credit', type: 'string', note: '출처 명시' },
      { name: 'status', type: 'string', enum: ['visible', 'hidden', 'reported'] },
    ],
  },
  StoreReview: {
    name: '안심 후기', description: '5L 안심지표(별점 아님 — 매장만). 포인트·코인 적립',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'storeId', type: 'string', format: 'uuid', required: true },
      { name: 'authorId', type: 'string', format: 'uuid', required: true },
      { name: 'scores', type: 'object', note: '5L 슬라이더' },
      { name: 'content', type: 'string', required: true, note: '경험메모(필수)' },
      { name: 'anonymous', type: 'boolean', example: true },
      { name: 'status', type: 'string', enum: ['visible', 'hidden', 'reported', 'pending'], required: true },
    ],
  },
  StoreList: {
    name: '장소 모음(책장)', description: '핵심 소셜 오브젝트 — 부모가 모은 안심장소 큐레이션. 팔로우·구독(별점/순위 없음)',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'ownerId', type: 'string', format: 'uuid', required: true },
      { name: 'title', type: 'string', required: true, example: '일산 감각친화 나들이' },
      { name: 'isPublic', type: 'boolean', required: true },
      { name: 'itemsCount', type: 'integer' },
      { name: 'subscribersCount', type: 'integer' },
      { name: 'items', type: 'array', note: 'StoreListItem(storeId·메모)' },
    ],
  },
  RespiteBooking: {
    name: '시간제 돌봄 예약(일감)', description: '🔒 부모↔돌보미 매칭·예약. 자녀 평문 미기록(childId로만). 수락 전 마스킹',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'parentId', type: 'string', format: 'uuid', required: true },
      { name: 'childId', type: 'string', format: 'uuid', required: true, note: '🔒 수락 전 이름·연락처 마스킹' },
      { name: 'partnerId', type: 'string', format: 'uuid', note: '돌보미(수락 시 배정)' },
      { name: 'requestedStart', type: 'datetime', required: true },
      { name: 'requestedEnd', type: 'datetime', required: true },
      { name: 'fee', type: 'integer', note: '시급 15,000원 기준' },
      { name: 'notes', type: 'string', note: '🔒 특이사항(보관·파기 고지)' },
      { name: 'status', type: 'string', enum: ['requested', 'matched', 'confirmed', 'in_progress', 'completed', 'cancelled', 'no_match'], required: true, note: '수락=requested→matched 선점(0행이면 마감)' },
    ],
  },
  Settlement: {
    name: '정산', description: '🔒 돌보미 회차 정산 — 원천징수 3.3%·net 정합강제(불일치 시 확정/지급 차단)·코인분',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'partnerId', type: 'string', format: 'uuid', required: true, note: 'unique(partnerId,period)' },
      { name: 'period', type: 'string', example: '2026-10' },
      { name: 'gross', type: 'integer' },
      { name: 'withholding', type: 'integer', note: '원천징수 3.3%' },
      { name: 'net', type: 'integer', note: 'net = gross − withholding (정합 강제)' },
      { name: 'coinPortion', type: 'integer' },
      { name: 'status', type: 'string', enum: ['pending', 'confirmed', 'paid', 'hold'], required: true },
      { name: 'paidAt', type: 'datetime', note: '지급 후 되돌림 시 사유필수·이력보존' },
    ],
  },
  Wallet: {
    name: '지갑(코인·포인트)', description: '도담 코인(폐쇄형 마일리지·환금불가·12개월) + 포인트(등급 산정). 클로백=음수 엔트리',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'profileId', type: 'string', format: 'uuid', required: true },
      { name: 'coinBalance', type: 'integer', note: '1코인≈1,000원 참고(현금 환금 불가)' },
      { name: 'points', type: 'integer', note: '후기+50P·일지+150P → 등급' },
      { name: 'ledger', type: 'array', note: 'CoinLedger(delta·reason·refType·balanceAfter)' },
    ],
  },
  AffinityReview: {
    name: '친화도 후기(앰배서더)', description: '매장=평점 / 병원=평점 금지(의료법 — scores NULL 강제). 무급·사실기반·금칙어 차단',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'ambassadorId', type: 'string', format: 'uuid', required: true },
      { name: 'targetType', type: 'string', enum: ['store', 'hospital'], required: true },
      { name: 'storeId', type: 'string', format: 'uuid' },
      { name: 'targetName', type: 'string' },
      { name: 'scores', type: 'object', note: '병원이면 NULL 강제(의료법 무평점)' },
      { name: 'content', type: 'string', note: '≥10자·금칙어 실시간 차단' },
      { name: 'status', type: 'string', enum: ['pending', 'approved', 'hidden'], required: true },
    ],
  },
  Membership: {
    name: '멤버십·결제(도담 패스)', description: '월 990원 후원(실 PG 미연동 — 상태·UI만·수동). 소프트게이트: 글쓰기·1:1·구독·후기',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'profileId', type: 'string', format: 'uuid', required: true },
      { name: 'tier', type: 'string', enum: ['free', 'pass'], required: true },
      { name: 'amount', type: 'integer', example: 990 },
      { name: 'cycle', type: 'string', enum: ['monthly'], note: '구독 주기' },
      { name: 'status', type: 'string', enum: ['active', 'canceled', 'expired'], required: true },
      { name: 'cancelReason', type: 'string', note: '관리자 강제해지 시 필수' },
      { name: 'payment', type: 'object', note: '🔒 Payment(amount·method pg/card/manual·status·refundReason) — PG 미연동' },
    ],
  },
  SelfCheckTemplate: {
    name: '자가진단 템플릿·응답', description: '🔒 비진단 자기점검. 비진단 고지 동의 게이트(스킵불가)·published+license_verified만 채점·결과=상담권고',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'title', type: 'string', example: '우리 아이 살펴보기' },
      { name: 'domain', type: 'string', note: '언어·감각·사회성 등' },
      { name: 'questions', type: 'array', note: '문항(yesno/scale·채점·밴드·의뢰기준·면책)' },
      { name: 'licenseVerified', type: 'boolean', required: true, note: '외부도구(K-DST) 실문항 배포 게이트' },
      { name: 'disclaimer', type: 'string', required: true, note: '비진단 고지' },
      { name: 'status', type: 'string', enum: ['draft', 'verified', 'published', 'retired'] },
      { name: 'responseConsent', type: 'boolean', note: '🔒 응답 산출 전 동의(없으면 차단) — 응답 원자료는 콘솔 미조회·집계만' },
    ],
  },
  SafetyIncident: {
    name: '안전 사건', description: '🔒 SOS·발작·멜트다운 등 현장 사건. 분류→상신→해결(해결메모 필수). 신고자엔 상태만·조치메모 미노출',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'bookingId', type: 'string', format: 'uuid', note: 'RespiteBooking FK(해당 시)' },
      { name: 'reporterId', type: 'string', format: 'uuid', required: true },
      { name: 'type', type: 'string', enum: ['seizure', 'choking', 'injury', 'other'], required: true },
      { name: 'severity', type: 'string', enum: ['low', 'mid', 'high'], required: true },
      { name: 'description', type: 'string', note: '🔒' },
      { name: 'status', type: 'string', enum: ['reported', 'triage', 'handling', 'escalated', 'resolved'], required: true },
      { name: 'resolution', type: 'string', note: '해결메모(필수) — 내부용' },
      { name: 'handledBy', type: 'string', format: 'uuid' },
    ],
  },
  Report: {
    name: '신고·모더레이션', description: '커뮤니티글·후기·프로필·매장 등 신고 → 검토/기각/조치(숨김·노출중단·정지)',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'targetType', type: 'string', enum: ['community_post', 'store_review', 'comment', 'profile', 'partner', 'store'], required: true },
      { name: 'targetId', type: 'string', format: 'uuid', required: true },
      { name: 'reason', type: 'string', required: true },
      { name: 'status', type: 'string', enum: ['open', 'reviewing', 'actioned', 'dismissed'], required: true },
      { name: 'action', type: 'object', note: 'ModerationAction(action·adminId·note 필수)' },
    ],
  },
  StoryArticle: {
    name: '돌봄 이야기(콘텐츠)', description: 'CMS 발행글·부모 경험담. 3대축×5대영역·고충유형. 발행/보관/삭제',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'title', type: 'string', required: true },
      { name: 'domain', type: 'string', enum: ['place', 'living', 'medical', 'education', 'lifecycle'] },
      { name: 'body', type: 'string' },
      { name: 'source', type: 'string', note: '출처·발행일' },
      { name: 'status', type: 'string', enum: ['draft', 'published', 'archived'], required: true },
    ],
  },
  CommunityPost: {
    name: '커뮤니티 글', description: '부모 커뮤니티 — 자조·자유·Q&A·매거진. 자녀유형 칩·신고·댓글(대댓글)',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'authorId', type: 'string', format: 'uuid', required: true },
      { name: 'category', type: 'string', enum: ['자조', '자유', 'ask_expert', '매거진'] },
      { name: 'childType', type: 'string', note: '자녀유형 칩(비식별 표준 카테고리)' },
      { name: 'body', type: 'string' },
      { name: 'status', type: 'string', enum: ['visible', 'hidden', 'deleted'], required: true },
      { name: 'comments', type: 'array', note: 'CommunityComment(parentCommentId 대댓글)' },
    ],
  },
  PlaceSubmission: {
    name: '장소 제안·제보', description: '부모 안심장소 제안 / 데이터 생산자 필드리포트 → 검수→매장등록(+활동비 stipend)',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'submitterId', type: 'string', format: 'uuid', required: true },
      { name: 'raw', type: 'object', note: '장소·유형·지역·6축 접근성 메모·사진(동의)' },
      { name: 'stipend', type: 'integer', note: '승인 시 활동비' },
      { name: 'storeId', type: 'string', format: 'uuid', note: '승인 시 생성된 Store' },
      { name: 'status', type: 'string', enum: ['submitted', 'reviewing', 'approved', 'rejected'], required: true },
    ],
  },
  StorePartnerRequest: {
    name: '매장파트너 요청', description: '매장 claim(신규 소유권)/edit(수정)/inquiry(문의). 승인/반려(사유)',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'partnerId', type: 'string', format: 'uuid', required: true },
      { name: 'type', type: 'string', enum: ['claim', 'edit', 'inquiry', 'new'], required: true },
      { name: 'payload', type: 'object', note: '수정항목 diff·접근성·사진' },
      { name: 'status', type: 'string', enum: ['pending', 'approved', 'rejected'], required: true },
      { name: 'rejectReason', type: 'string' },
    ],
  },
  Region: {
    name: '지역', description: '시·도 › 구·군 › 동 3단계 계층(parent_id 자기참조). 삭제 대신 active 토글. 권역=일산·파주/고양',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'level', type: 'string', enum: ['city', 'district', 'dong'], required: true },
      { name: 'name', type: 'string', required: true, example: '일산동구' },
      { name: 'parentId', type: 'string', format: 'uuid', note: '자기참조' },
      { name: 'active', type: 'boolean', required: true, note: '삭제 대신 비활성' },
    ],
  },
  Announcement: {
    name: '공지', description: '대상별 공지(전체/부모/파트너/돌보미/앰배서더). 발행 시 notifyMany 팬아웃(MAX 20000)',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'audience', type: 'string', enum: ['all', 'parents', 'partners', 'caregivers', 'ambassadors'], required: true },
      { name: 'title', type: 'string', required: true },
      { name: 'body', type: 'string' },
      { name: 'status', type: 'string', enum: ['draft', 'published'], required: true },
    ],
  },
  Notification: {
    name: '알림', description: '매칭·심사·정산·교육·안전 등 알림. 서버+로컬 병합·미읽음 dot·자동읽음',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'recipientId', type: 'string', format: 'uuid', required: true },
      { name: 'type', type: 'string', example: 'booking_matched' },
      { name: 'refType', type: 'string' },
      { name: 'refId', type: 'string', format: 'uuid' },
      { name: 'read', type: 'boolean', required: true },
    ],
  },
  AdminUser: {
    name: '관리자(콘솔 RBAC)', description: '5역할+메뉴권한 매트릭스. 전 쓰기=logAudit·민감열람=logView. superadmin만 관리자관리',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'email', type: 'string', format: 'email', required: true },
      { name: 'adminRole', type: 'string', enum: ['superadmin', 'reviewer', 'moderator', 'finance', 'support'], required: true },
      { name: 'permissions', type: 'object', required: true, note: '{ menus:[], readonly:bool } — 역할 capability ∩ 부여메뉴(이중방어)' },
    ],
  },
  AuditLog: {
    name: '감사 로그', description: '전 관리자 액션 추적(불변식). 시각·행위자·액션·대상·변경 전/후 JSON·IP',
    fields: [
      { name: 'id', type: 'string', format: 'uuid', required: true },
      { name: 'actorId', type: 'string', format: 'uuid', required: true },
      { name: 'action', type: 'string', example: 'partner.approve' },
      { name: 'entity', type: 'string', note: '대상 엔티티·ID' },
      { name: 'before', type: 'object' },
      { name: 'after', type: 'object' },
      { name: 'ip', type: 'string' },
    ],
  },
};
