/* 도담 PRD v2.0.0 — 렌더용 미러. 정본은 docs/PRD.md.
 * 실서비스 dodam-app(부모앱·파트너스앱·관리자) 3채널 기준. */
window.PLANDECK_PRD = {
  version: '2.0.0',
  northStar: '발달장애 아동 가족이 실제 다녀와 검증한 장소(감각·응대·환대 접근성)를 쌓고, 비슷한 상황의 부모를 팔로우·구독하며 신뢰 기반으로 연결되는 지역 밀착 생활 커뮤니티. 장소는 진입점, 커뮤니티가 중심. (시간제돌봄·치료매칭은 레이어)',
  background:
    '발달장애 아동 가족은 "어디를 안심하고 갈 수 있는지" "누구에게 잠시 맡길 수 있는지" 정보가 흩어져 있고 검증이 없다. 물리적 접근성(휠체어)이 아니라 감각·응대·정서 접근성이 핵심인데 이를 다루는 서비스가 국내에 공백. 도담은 좁은 지역(일산·파주/고양)을 깊게 — 검증 장소 밀도와 부모 밀도를 먼저 쌓아 신뢰 커뮤니티를 만든다.',
  goals: [
    '부모가 "아이와 함께 갈 곳(안심매장)"과 "잠시 안심하고 맡기기(시간제돌봄)"를 신뢰 기반으로 찾는다',
    '부모가 검증 장소를 모으고(책장) 비슷한 부모를 팔로우·구독하는 생활 커뮤니티',
    '공급자(돌보미·앰배서더·매장)를 검증 파이프라인으로 안전하게 온보딩',
    '운영자가 심사·안전·정산·콘텐츠를 RBAC·감사 기반으로 운영',
    '민감정보(자녀 장애) 기본 비공개·별도 동의로 "안심하고 쓸 수 있는" 플랫폼',
  ],
  users: [
    { role: '부모(수요측)', need: '아이에게 안전한 장소·돌봄을 신뢰 기반으로 찾고, 비슷한 부모와 연결되고 싶다', channel: '부모앱' },
    { role: '돌보미(공급·유급)', need: '검증을 거쳐 시간제 돌봄 일감을 받고 정산받고 싶다', channel: '파트너스앱' },
    { role: '앰배서더(공급·무급)', need: '봉사·친화도 후기로 지역 장소 신뢰를 함께 쌓고 싶다', channel: '파트너스앱' },
    { role: '매장파트너', need: '우리 가게를 발달장애 친화 매장으로 등록·관리하고 싶다', channel: '파트너스앱' },
    { role: '운영자(5역할)', need: '공급자·장소를 심사하고 안전·정산·콘텐츠를 안전하게 운영하고 싶다', channel: '관리자 콘솔' },
  ],
  scope: {
    includes: [
      '부모앱: 홈(2대 시나리오)·안심매장 탐색/상세/지도·방문예약·시간제돌봄 매칭/예약·치료예약·동행(품앗이)·상담·자녀허브·돌봄일지·자가진단(비진단)·시그널카드·SOS·커뮤니티(글/Q&A/아빠교실/장소제안)·돌봄이야기(콘텐츠)·이벤트·장소모음(책장)·후기·앰배서더·지갑(코인/포인트)·마이·알림·개인정보/약관',
      '파트너스앱: 역할 온보딩 검증 파이프라인(역할→자격→동의/서류→성범죄경력조회→보험/봉사동의→안전교육)·심사현황·일감(매칭/일정/가용)·일감상세(마스킹)·정산(3.3%)/계좌/세금·매장 등록/수정/후기·봉사·친화도후기(병원 무평점)·공동창조·등급·교육·SOP·마이',
      '관리자: 대시보드(처리대기 9큐)·활성화 드릴다운·파트너 심사(3게이트)·장소 제출/매장파트너 검수·매장 인증(6축)·사용자·예약·정산·안전·모더레이션·콘텐츠(CMS)·셀프체크·친화도검수·지역·멤버십·공지·공동창조·감사로그·관리자관리',
    ],
    excludes: ['실 PG 결제(멤버십=상태·UI만·수동)', '커머스/공동구매(P2 문서화만)', '전국 확장(권역=일산·파주/고양 한정)', '실시간 영상 상담'],
  },
  successMetrics: [
    { metric: '검증 장소 밀도', target: '권역 내 안심매장 Gold/Silver 밀도(핵심 신뢰자산)' },
    { metric: '부모 밀도·소셜', target: '장소모음(책장) 생성·구독·팔로우(활성 KPI 소스)' },
    { metric: '첫 가치 도달', target: '첫 안심매장/돌봄 탐색까지 마찰 최소' },
    { metric: '공급 안전', target: '돌보미 3게이트(성범죄경력·보험·교육) verified 100%' },
    { metric: '접근성', target: 'WCAG 2.1 AA(도담 정체성 — 고령·보조기기 포함)' },
  ],
  constraints: [
    '민감정보(자녀 장애·중증도·감각) = 건강정보: 전면 선택입력·기본 비공개·별도 동의 없으면 write 거부',
    '지도 API 응답 영속저장 금지(실시간 재호출) — 장소는 자체축적/공공데이터',
    '비가역 쓰기(정산 지급·심사 승인/반려·안전 상신·신고 조치·공지 팬아웃)는 사유필수·확인·감사(logAudit)',
    '병원·의사 후기 = 평점 금지(의료법) · 자가진단 = 비진단(진단/병명 금지)',
  ],
  assumptions: [
    '3앱은 라이브 Supabase `dodam` 스키마를 단일 진실원으로 공유(콘솔 변경→앱 즉시 반영)',
    '부모=모바일 무로그인 둘러보기 가능, 쓰기 시 로그인. 파트너=승인 전 게이트. 관리자=requireAdmin+RBAC',
    '서비스 권역=일산·파주/고양(regions DB 구동)',
  ],
  dependencies: ['Supabase(Auth·DB·RLS·서버액션)', '카카오 로컬/지도(bbox 일산·파주)', '성범죄경력 조회(아청법·경찰관서)', '배상책임보험사', '푸시 알림', '향후 PG(미연동)'],
  nfr: {
    accessibility: 'WCAG 2.1 AA(도담 정체성). focus-visible·prefers-reduced-motion·forced-colors·aria-live(SPA 제목 발화)·landmark·skip-link·터치≥44px·타이포 12px 미만 금지·상태는 색만으로 전달 금지(아이콘·라벨 병행)',
    pwa: '모바일 480px 앱셸 PWA(부모·파트너). 오프라인·설치·업데이트',
    safety: 'SOS 상시 119/112 실연결(전 화면 FAB)·비상연락망 원탭·시그널카드(해바라기+QR 토큰). 안전사건 분류→상신→해결(해결메모 필수)',
    security: 'RLS·서버액션 권한 게이트·민감정보 최소수집/암호화/마스킹·성범죄경력 결과만(원본 미저장)·서류 파일 미저장(attestation)·전 쓰기 logAudit·민감열람 logView',
    performance: '지역 밀착 — 권역 내 탐색 빠르게. 지도 실시간 재호출 캐시 전략',
    design: '디자인시스템 "고요한 안심(Quiet Companion)" — Forest green #264E3C + Clay #B45E2B 2-accent, Warm Paper 표면. 이모지→플랫 라인아이콘(EMOJI_TO_ICON 룰). 타이포 7단계 하드룰',
  },
  rbac: {
    parent: '기본 수요측. 무로그인 둘러보기·검색·예약 미리보기 가능(쓰기 시 로그인). 등급=포인트(새싹/실버/골드)',
    partner: 'kind 3역할 상호배제: 돌보미(유급·검증 파이프라인·일감/정산)·앰배서더(무급·봉사/친화도후기/공동창조)·매장파트너(돌봄게이트 없음·매장). 미승인=게이트',
    membership: 'free / pass(990원) 소프트게이트: 글쓰기·1:1·구독·후기(둘러보기·검색은 항상 무료)',
    admin: '5역할 capability 매트릭스(lib/permissions.ts SSOT): superadmin(전체+관리자관리 유일)·reviewer(심사)·moderator(모더·안전·콘텐츠)·finance(정산·멤버십)·support(사용자·예약·지역·감사). 권한=부여메뉴 ∩ 역할capability(이중방어). readonly 모드. TOTP 표시전용',
  },
  privacy: {
    sensitive: '자녀 장애유형·중증도·감각프로파일=건강정보(G1). 기본 비공개·항목별 공개범위(private/group/public)·별도 동의(sensitiveConsent)·건강정보 없이도 핵심기능 동작',
    minor: '만 14세 미만 법정대리인 동의(guardianConsent) · 돌봄 예약 시 미성년 위탁 동의+법적전문 필수',
    masking: '예약 수락 전 자녀 이름·연락처 마스킹(childId로만 연계) · 공개 시 ageBand·표준카테고리로 de-identify',
    rights: '정보주체 권리 — 내 정보 관리(보관서류·동의내역·사본받기·탈퇴/파기). 셀프체크 응답 원자료는 콘솔 미조회(집계만)',
  },
  regulation: {
    G1_PIPA: '민감정보 — 위 privacy 계약',
    G2_selfcheck: '자가진단=비진단. 진단/병명/확정 금지·금칙어 필터·비진단 고지 동의 게이트(스킵불가)·결과=상담권고+자원. 외부도구(K-DST)는 license_verified 전 실문항 배포 금지',
    G3_copyright: '장소=자체축적/공공데이터(지도 응답 영속저장 금지)·사진=직접촬영/업로더 동의/출처 중 하나·consent 미체크 차단·신고→삭제',
    G4_medical: '병원·의사 후기 평점 금지(별점/순위 없음·병원 scores NULL 강제)·무급·사실기반·금칙어 실시간 차단·고지 동의',
    background_check: '돌보미 성범죄경력 조회(아청법)=경찰관서 주체·도담은 결과만·원본 미저장. 돌보미 승인은 성범죄/보험/교육 3게이트 verified 필수',
    settlement: '정산 원천징수 3.3%·net=gross−withholding 정합강제(불일치 차단)·지급 되돌림 사유필수·코인 환금불가. 계좌번호 현행 미수집(암호화 경로 전)',
    payment: '도담패스=실 PG 미연동·가짜성공 금지("준비 중/수동" 표기)',
  },
  alternatives: {
    competitors: [
      { name: '맘카페·네이버 블로그', limit: '발달장애 특화 아님·검증 없음·감각/응대 접근성 데이터 없음·휘발' },
      { name: '복지관·바우처', limit: '공급 부족·대기·일상 장소/돌봄 공백·커뮤니티 없음' },
      { name: '일반 돌봄 매칭앱', limit: '발달장애 특수성·안전검증·민감정보 보호 미흡' },
    ],
    differentiation: '감각·응대·정서 접근성 데이터 + 부모 검증 커뮤니티(책장·팔로우) + 공급 안전검증(성범죄경력/보험/교육) + 지역 밀착. 국내 공백 영역',
    wtp: '도담패스 월 990원(매출 아닌 어뷰징 필터·실사용자 식별). 수익은 돌봄 중개수수료·데이터 생산 활동비·향후 제휴. 좁은 권역 깊게로 밀도 선확보',
    risk: '양면시장 — 장소/부모 밀도와 공급 밀도를 동시에 쌓아야. 권역 한정으로 초기 밀도 집중(하방 방어)',
  },
  releases: [
    { phase: 'Now(일산·파주/고양)', items: ['안심매장 탐색·검증', '시간제돌봄 매칭', '부모 커뮤니티·책장', '공급 온보딩 검증', '관리자 심사·안전·정산'] },
    { phase: '정식화 대상', items: ['멤버십 실 PG', '자가진단 실문항(license_verified)', '시그널카드 토큰 실검증', '심사 이의제기(appeal) 플로우'] },
    { phase: 'P2', items: ['커머스·공동구매', '권역 확장'] },
  ],
  requirements: [
    // 부모앱
    { id: 'REQ-P01', title: '홈 2대 시나리오·개인화 허브', surface: 'parent' },
    { id: 'REQ-P02', title: '안심매장 탐색·필터·지도', surface: 'parent' },
    { id: 'REQ-P03', title: '매장 상세(6축 접근성·적합도·후기·예약)', surface: 'parent' },
    { id: 'REQ-P04', title: '안심 방문 예약', surface: 'parent' },
    { id: 'REQ-P05', title: '시간제돌봄 조건·요금견적·돌보미 매칭·예약', surface: 'parent' },
    { id: 'REQ-P06', title: '치료 예약', surface: 'parent' },
    { id: 'REQ-P07', title: '동행(또래 부모 품앗이)', surface: 'parent' },
    { id: 'REQ-P08', title: '1:1 상담(치료사)', surface: 'parent' },
    { id: 'REQ-P09', title: '자녀 등록·허브·개인화(민감정보 동의 게이트)', surface: 'parent' },
    { id: 'REQ-P10', title: '자가진단(비진단 고지 동의·상담권고)', surface: 'parent' },
    { id: 'REQ-P11', title: '시그널카드(해바라기·QR·직원 검증뷰)', surface: 'parent' },
    { id: 'REQ-P12', title: 'SOS 긴급(119/112 실연결·비상연락)', surface: 'parent' },
    { id: 'REQ-P13', title: '돌봄 일지(방문 사후기록·포인트)', surface: 'parent' },
    { id: 'REQ-P14', title: '안심 후기(5L 지표·포인트/코인)', surface: 'parent' },
    { id: 'REQ-P15', title: '커뮤니티(글·Q&A·아빠교실·장소제안·댓글)', surface: 'parent' },
    { id: 'REQ-P16', title: '돌봄 이야기(콘텐츠 허브·주제/유형)', surface: 'parent' },
    { id: 'REQ-P17', title: '장소 모음(책장)·팔로우·구독', surface: 'parent' },
    { id: 'REQ-P18', title: '이벤트(지역 행사)', surface: 'parent' },
    { id: 'REQ-P19', title: '지갑(코인·포인트·등급·교환)', surface: 'parent' },
    { id: 'REQ-P20', title: '마이·보호자 프로필·공개범위·데이터 권리', surface: 'parent' },
    { id: 'REQ-P21', title: '도담패스(월 990원·실PG 미연동)', surface: 'parent' },
    { id: 'REQ-P22', title: '알림·비상연락망 설정', surface: 'parent' },
    { id: 'REQ-P23', title: '로그인·온보딩·약관/개인정보처리방침', surface: 'parent' },
    // 파트너스앱
    { id: 'REQ-T01', title: '역할 온보딩(역할선택→자격→동의/서류)', surface: 'partner' },
    { id: 'REQ-T02', title: '성범죄경력 조회 동의(아청법)', surface: 'partner' },
    { id: 'REQ-T03', title: '배상책임보험(돌보미)·무급 봉사동의(앰배서더)', surface: 'partner' },
    { id: 'REQ-T04', title: '안전교육 이수(4모듈+퀴즈)·심사현황', surface: 'partner' },
    { id: 'REQ-T05', title: '매장파트너 가입(돌봄게이트 없음)', surface: 'partner' },
    { id: 'REQ-T06', title: '일감(매칭/일정/가용시간)·상세(수락 전 마스킹)', surface: 'partner' },
    { id: 'REQ-T07', title: '정산(3.3% 원천징수)·계좌주기·세금안내', surface: 'partner' },
    { id: 'REQ-T08', title: '매장 등록/수정요청/후기(매장파트너)', surface: 'partner' },
    { id: 'REQ-T09', title: '봉사·친화도후기(병원 무평점)·공동창조(앰배서더)', surface: 'partner' },
    { id: 'REQ-T10', title: '마이·프로필·등급·교육·정보관리·SOP', surface: 'partner' },
    // 관리자
    { id: 'REQ-A01', title: '대시보드(처리대기 9큐·활성화 드릴다운)', surface: 'admin' },
    { id: 'REQ-A02', title: '파트너 심사(성범죄/보험/교육 3게이트·승인/반려)', surface: 'admin' },
    { id: 'REQ-A03', title: '장소 제출·매장파트너 요청 검수', surface: 'admin' },
    { id: 'REQ-A04', title: '매장 인증 심사(6축 현장채점·확정등급)', surface: 'admin' },
    { id: 'REQ-A05', title: '사용자 관리(조회·정지/복구)', surface: 'admin' },
    { id: 'REQ-A06', title: '예약·매칭 모니터링·개입', surface: 'admin' },
    { id: 'REQ-A07', title: '정산·코인(회차 배치·net 정합·클로백)', surface: 'admin' },
    { id: 'REQ-A08', title: '안전 사건(분류→상신→해결)', surface: 'admin' },
    { id: 'REQ-A09', title: '신고·모더레이션(숨김·노출중단·정지)', surface: 'admin' },
    { id: 'REQ-A10', title: '콘텐츠 CMS·경험담·커뮤니티 모더', surface: 'admin' },
    { id: 'REQ-A11', title: '자가진단 템플릿 검수·발행(비진단 게이트)', surface: 'admin' },
    { id: 'REQ-A12', title: '친화도 평가 검수(병원 무평점)', surface: 'admin' },
    { id: 'REQ-A13', title: '지역 관리(시·구·동 계층)', surface: 'admin' },
    { id: 'REQ-A14', title: '멤버십·결제(데모·환불)', surface: 'admin' },
    { id: 'REQ-A15', title: '공지(대상별 팬아웃)·아빠교실·공동창조', surface: 'admin' },
    { id: 'REQ-A16', title: '감사로그·관리자 관리(superadmin)', surface: 'admin' },
    { id: 'REQ-A17', title: '운영 콘솔 로그인(관리자 여부 검증)', surface: 'admin' },
  ],
  workflows: [
    '부모 안심매장: 홈/매장 → 상세(6축·적합도) → 담기(책장)/예약 → 방문 후 일지/후기',
    '부모 시간제돌봄: 조건·요금 → 돌보미 매칭(예약시트: 비상연락·미성년위탁 동의) → 예약완료 → 수락 대기',
    '부모 안전: 전화면 SOS FAB → 119/112·비상연락 / 시그널카드(해바라기·QR) → 직원 검증뷰',
    '파트너 온보딩: 역할→자격→동의/서류→성범죄경력조회→보험/봉사동의→교육 → 심사현황 → (관리자 3게이트 승인) → 앱 진입',
    '파트너 일감: 매칭요청 → 상세(마스킹) → 수락(선점: requested→matched) → 실명·연락처 공개 → 정산',
    '관리자 심사: 대시보드 큐 → 파트너(3게이트 verified·승인/반려 사유) / 장소(6축 현장채점·인증) → 앱 노출',
    '관리자 안전·정산: 안전사건(분류→상신→해결 메모) / 정산(회차 일괄확정→지급·net 정합)',
  ],
  resolvedDecisions: [
    '컨셉 = 장소 진입점·커뮤니티 중심(돌봄/치료는 레이어)',
    '권역 = 일산·파주/고양(regions DB 구동) — 좁게 깊게',
    '멤버십 = 월 990원·실PG 미연동(어뷰징 필터 목적)·코인 폐쇄형',
    '병원 무평점·자가진단 비진단 = 규제 게이트 확정',
  ],
  openQuestions: [
    '서비스 권역 표기 통일 — 코드(일산·파주) vs PRD서술(일산·고양) 확정 필요',
    '심사 이의제기(appeal) 플로우 — 현행 미구현(반려=terminal). v2에서 정식화 대상',
    '멤버십 실 PG·자가진단 실문항(license)·시그널카드 토큰 실검증 — 정식화 시점',
  ],
};
window.PDK_PRD = window.PLANDECK_PRD;
