/* 도담 v2.0.0 — 부모앱 채널 화면 메타(SSOT). 공통 컴포넌트(engine/pd-components.js) 조립.
 * surface:'parent'(모바일). 파트너스앱·관리자 채널은 순차 추가. id=SCR-PARENT-NNN. */
window.PLANDECK_SCREENS = [
  {
    category: '부모앱 (모바일)',
    pages: [
      {
        id: 'SCR-PARENT-001', label: '홈', href: 'p-home.html',
        surface: 'parent', entry: true, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P01'],
        context: '2대 시나리오(갈 곳/맡기기)+개인화 허브. 로그인 없이 둘러보기 가능.',
        components: [
          { role: '.pd-searchbar', kind: 'input', label: '통합 검색' },
          { role: '.pd-tiles', kind: 'tiles', label: '2대 시나리오' },
          { role: '.pd-list', kind: 'list', label: '맞춤 추천(매장·모음·이야기)' },
        ],
        description: [
          { text: '검색 — 매장·돌봄·이야기 통합', target: '.pd-searchbar' },
          { text: '갈 곳(안심매장)·맡기기(돌봄) 2대 시나리오', target: '.pd-tiles' },
          { text: '맞춤 안심매장·동네 모음·이야기·이벤트', target: '.pd-list' },
        ],
        cases: [
          { state: '정상', trigger: '진입', guard: '', result: '개인화 홈', message: '', api: { endpoint: 'GET /app/home', status: 200 } },
          { state: '비로그인', trigger: '진입', guard: '세션 없음', result: '둘러보기(일반 추천)', message: '', placement: 'inline' },
          { state: '빈데이터', trigger: '진입', guard: '자녀 미등록', result: '자녀 등록 유도', message: '우리 아이를 등록하면 맞춤 추천을 받을 수 있어요', placement: 'inline' },
        ],
        interface: { reads: [{ id: 'home', intent: '홈 개인화', method: 'GET', path: '/app/home', response: '{ stores:{entities.Store}[], lists:{entities.StoreList}[], stories:{entities.StoryArticle}[] }', auth: 'Optional', target: '.pd-list' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-004', via: '갈 곳' }, { screen: 'SCR-PARENT-009', via: '맡기기' }, { screen: 'SCR-PARENT-020', via: '시그널카드' }] },
      },
      {
        id: 'SCR-PARENT-002', label: '로그인', href: 'p-login.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P23'],
        context: 'Supabase 이메일/비번. 쓰기(글·예약) 시 로그인 유도, 둘러보기는 무로그인.',
        components: [{ role: '.pd-login', kind: 'form', label: '로그인 폼' }],
        description: [{ text: '이메일·비밀번호·가입', target: '.pd-login' }],
        cases: [
          { state: '초기', trigger: '진입', guard: '', result: '로그인 폼', message: '', target: '.pd-login' },
          { state: '필수누락', trigger: '로그인', guard: '미입력', result: '막음', message: '이메일과 비밀번호를 입력해 주세요', placement: 'inline', target: '.pd-login', priority: 'P1' },
          { state: '권한없음', trigger: '로그인', guard: '자격 불일치', result: '막음', message: '이메일 또는 비밀번호를 확인해 주세요', placement: 'inline', priority: 'P1' },
          { state: '유효', trigger: '로그인', guard: '정상', result: '세션 생성·복귀', message: '', priority: 'P0', api: { endpoint: 'POST /auth/login', status: 200 } },
        ],
        interface: { reads: [], writes: [{ id: 'login', intent: '로그인', method: 'POST', path: '/auth/login', response: '{ token:string, profile:{entities.Profile} }', errors: [{ status: 401, when: '자격 불일치', message: '이메일 또는 비밀번호를 확인해 주세요' }], auth: 'None', target: '.pd-login' }], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-003', via: '가입' }] },
      },
      {
        id: 'SCR-PARENT-003', label: '우리 아이 맞춤 설정', href: 'p-onboarding.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P09'],
        context: '아이 등록·개인화 시드. 민감정보(장애) 기본 비공개·별도 동의·14세 미만 법정대리인 동의 게이트(PIPA G1).',
        components: [{ role: '.pd-form', kind: 'form', label: '아이 기본·배려 입력' }, { role: '.pd-check', kind: 'consent', label: '민감정보·법정대리인 동의' }],
        description: [
          { text: '유형·중증도=선택·건강정보', target: '.pd-form' },
          { text: '민감정보 처리 동의(필수)·14세 미만 법정대리인 동의(필수)', target: '.pd-check' },
        ],
        cases: [
          { state: '정상', trigger: '진입', guard: '', result: '설정 마법사', message: '', target: '.pd-form' },
          { state: '필수누락', trigger: '완료', guard: '민감정보 동의 미체크', result: '막음', message: '민감정보 처리 동의가 필요해요(동의 없이는 저장되지 않음)', placement: 'inline', target: '.pd-check', priority: 'P0' },
          { state: '권한없음', trigger: '완료', guard: '14세 미만·법정대리인 미동의', result: '막음', message: '만 14세 미만은 법정대리인 동의가 필요해요', placement: 'inline', target: '.pd-check', priority: 'P0' },
          { state: '유효', trigger: '완료', guard: '동의 완료', result: '아이 등록·기본 비공개', message: '맞춤 설정이 완료됐어요', placement: 'toast', priority: 'P0', api: { endpoint: 'POST /app/children', status: 201 } },
        ],
        interface: { reads: [], writes: [{ id: 'createChild', intent: '아이 등록', method: 'POST', path: '/app/children', request: '{entities.Child}', response: '{entities.Child}', errors: [{ status: 422, when: '민감정보/법정대리인 미동의', message: '동의가 필요해요' }], auth: 'Bearer', target: '.pd-form' }], events: [{ name: 'consent.sensitive.granted', when: '민감정보 동의 시', payload: '{ childId, purpose, guardian:boolean }' }] },
        flow: { to: [{ screen: 'SCR-PARENT-001', via: '설정 완료' }] },
      },
      {
        id: 'SCR-PARENT-004', label: '안심 매장 찾기', href: 'p-stores.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P02'],
        context: '검증 안심매장 탐색 — 6축/유형/거리/등급/예약·검증 필터, 안심/전체 세그, 지도. 권역 일산·파주.',
        components: [
          { role: '.pd-searchbar', kind: 'input', label: '매장·지역 검색' },
          { role: '.pd-toolbar', kind: 'toolbar', label: '6축·유형·거리·등급 필터' },
          { role: '.pd-list', kind: 'list', label: '매장 리스트' },
        ],
        description: [
          { text: '검색·안심/전체 세그', target: '.pd-searchbar' },
          { text: '6축 접근성 등 필터', target: '.pd-toolbar' },
          { text: '매장 카드(등급·적합·지역)', target: '.pd-list' },
        ],
        cases: [
          { state: '정상', trigger: '진입', guard: '', result: '매장 목록', message: '', target: '.pd-list', api: { endpoint: 'GET /app/stores', status: 200 } },
          { state: '빈데이터', trigger: '필터', guard: '조건 결과 없음', result: '빈 상태', message: '조건에 맞는 안심매장이 아직 없어요', placement: 'inline', target: '.pd-list' },
          { state: '에러', trigger: '지도', guard: '지도 로드 실패', result: '리스트 폴백', message: '지도를 불러오지 못했어요. 목록으로 볼게요', placement: 'inline', priority: 'P2' },
        ],
        interface: { reads: [{ id: 'listStores', intent: '매장 탐색', method: 'GET', path: '/app/stores', params: [{ in: 'query', name: 'axis', type: 'string', required: false, example: 'sensory' }, { in: 'query', name: 'grade', type: 'string', required: false }, { in: 'query', name: 'region', type: 'string', required: false }, { in: 'query', name: 'cursor', type: 'string', required: false }], response: '{ stores:{entities.Store}[], nextCursor:string }', auth: 'Optional', target: '.pd-list' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-005', via: '매장' }] },
      },
      {
        id: 'SCR-PARENT-005', label: '매장 상세', href: 'p-store-detail.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P03'],
        context: '6축 접근성·우리아이 적합도·안심후기·장소모음 담기·방문예약. 병원은 평가지표 숨김(의료법 G4).',
        components: [
          { role: '.pd-banner', kind: 'banner', label: '우리 아이 적합도' },
          { role: '.pd-list', kind: 'list', label: '6축 접근성·후기' },
          { role: '.pd-cta-bar', kind: 'button', label: '방문 예약 CTA' },
        ],
        description: [
          { text: '적합도·6축 접근성', target: '.pd-list' },
          { text: '방문 예약', target: '.pd-cta-bar' },
        ],
        cases: [
          { state: '정상', trigger: '진입', guard: '', result: '매장 상세', message: '', api: { endpoint: 'GET /app/stores/{id}', status: 200 } },
          { state: '정상', trigger: '진입', guard: '병원·의원', result: '평가지표 숨김(경험만)', message: '', placement: 'inline' },
          { state: '빈데이터', trigger: '진입', guard: '접근성 미입력', result: '정보 없음 표기', message: '아직 접근성 정보가 없어요', placement: 'inline' },
        ],
        interface: { reads: [{ id: 'getStore', intent: '매장 상세', method: 'GET', path: '/app/stores/{id}', response: '{entities.Store}', auth: 'Optional' }, { id: 'storeReviews', intent: '안심 후기', method: 'GET', path: '/app/stores/{id}/reviews', response: '{entities.StoreReview}[]', auth: 'Optional' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-012', via: '방문 예약' }, { screen: 'SCR-PARENT-024', via: '후기' }, { screen: 'SCR-PARENT-031', via: '모음 담기' }] },
      },
      {
        id: 'SCR-PARENT-006', label: '우리 아이 돌봄', href: 'p-child.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P09'],
        context: '자녀 케어 허브 — 돌보미/치료/상담/동행·자가진단·치료 진척도·이웃부모 매칭.',
        components: [{ role: '.pd-tiles', kind: 'tiles', label: '돌봄·치료 진입' }, { role: '.pd-list', kind: 'list', label: '진척도·매칭' }],
        description: [{ text: '돌보미·치료·상담·동행', target: '.pd-tiles' }, { text: '치료 진척·이웃 매칭', target: '.pd-list' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '로그인', result: '케어 허브', message: '', api: { endpoint: 'GET /app/child-hub', status: 200 } },
          { state: '빈데이터', trigger: '진입', guard: '자녀 미등록', result: '등록 유도', message: '우리 아이를 먼저 등록해 주세요', placement: 'inline', target: '.pd-list' },
        ],
        interface: { reads: [{ id: 'childHub', intent: '케어 허브', method: 'GET', path: '/app/child-hub', response: '{ child:{entities.Child}, therapyProgress:object }', auth: 'Bearer' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-010', via: '돌보미' }, { screen: 'SCR-PARENT-014', via: '치료' }, { screen: 'SCR-PARENT-018', via: '상담' }, { screen: 'SCR-PARENT-016', via: '동행' }, { screen: 'SCR-PARENT-019', via: '살펴보기' }] },
      },
      {
        id: 'SCR-PARENT-007', label: '커뮤니티', href: 'p-community.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P15'],
        context: '부모 커뮤니티 — 자조·자유·전문가 Q&A·매거진·아빠교실·장소제안. 글쓰기는 도담패스(소프트게이트).',
        components: [{ role: '.pd-toolbar', kind: 'toolbar', label: '카테고리 탭' }, { role: '.pd-list', kind: 'list', label: '게시글 피드' }],
        description: [{ text: '카테고리 세그', target: '.pd-toolbar' }, { text: '게시글(자녀유형 칩·신고)', target: '.pd-list' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '', result: '피드', message: '', api: { endpoint: 'GET /app/community', status: 200 } },
          { state: '권한없음', trigger: '글쓰기', guard: '무료·비로그인', result: '도담패스 유도', message: '글쓰기는 도담 패스 후원으로 열려요', placement: 'inline', priority: 'P1' },
        ],
        interface: { reads: [{ id: 'listPosts', intent: '커뮤니티 피드', method: 'GET', path: '/app/community', params: [{ in: 'query', name: 'category', type: 'string', required: false }, { in: 'query', name: 'cursor', type: 'string', required: false }], response: '{ posts:{entities.CommunityPost}[], nextCursor:string }', auth: 'Optional', target: '.pd-list' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-026', via: '글' }, { screen: 'SCR-PARENT-027', via: '장소제안' }, { screen: 'SCR-PARENT-028', via: 'Q&A' }, { screen: 'SCR-PARENT-029', via: '아빠교실' }] },
      },
      {
        id: 'SCR-PARENT-008', label: '마이 도담', href: 'p-my.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P20'],
        context: '내 활동·설정 허브 — 지갑·모음·시그널카드·일지·예약내역·도담패스·정보/약관·돌보미 지원.',
        components: [{ role: '.pd-tiles', kind: 'tiles', label: '내 활동' }, { role: '.pd-list', kind: 'list', label: '예약·정보·약관' }],
        description: [{ text: '지갑·모음·시그널·일지', target: '.pd-tiles' }, { text: '예약내역·정보·약관', target: '.pd-list' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '로그인', result: '마이 허브', message: '', api: { endpoint: 'GET /app/my', status: 200 } },
          { state: '비로그인', trigger: '진입', guard: '세션 없음', result: '로그인 유도', message: '로그인하면 내 활동을 볼 수 있어요', placement: 'inline' },
        ],
        interface: { reads: [{ id: 'myHome', intent: '마이', method: 'GET', path: '/app/my', response: '{ profile:{entities.Profile}, bookings:object[] }', auth: 'Bearer' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-025', via: '지갑' }, { screen: 'SCR-PARENT-041', via: '도담패스' }, { screen: 'SCR-PARENT-022', via: '돌보미 지원' }, { screen: 'SCR-PARENT-042', via: '개인정보' }] },
      },
      {
        id: 'SCR-PARENT-009', label: '시간제 돌봄', href: 'p-respite.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P05'],
        context: '돌봄 조건(언제/시간/길이/장소) 선택·요금 견적(코인 시뮬)·책임/보험 고지.',
        components: [{ role: '.pd-form', kind: 'form', label: '조건 선택' }, { role: '.pd-cta-bar', kind: 'button', label: '돌보미 찾기' }],
        description: [{ text: '날짜·시간·길이·장소', target: '.pd-form' }, { text: '요금+코인 시뮬 → 매칭', target: '.pd-cta-bar' }],
        cases: [
          { state: '초기', trigger: '진입', guard: '자녀 선택', result: '조건 폼', message: '', target: '.pd-form' },
          { state: '권한없음', trigger: '찾기', guard: '비로그인', result: '로그인 유도', message: '예약은 로그인이 필요해요', placement: 'inline', priority: 'P1' },
          { state: '유효', trigger: '찾기', guard: '조건 완비', result: '돌보미 매칭', message: '', priority: 'P0' },
        ],
        interface: { reads: [{ id: 'respiteQuote', intent: '요금 견적', method: 'GET', path: '/app/respite/quote', params: [{ in: 'query', name: 'hours', type: 'number', required: true }], response: '{ fee:number, coinApplicable:number }', auth: 'Bearer' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-010', via: '돌보미 찾기' }] },
      },
      {
        id: 'SCR-PARENT-010', label: '돌보미 찾기', href: 'p-respite-match.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P05'],
        context: '검증 돌보미 매칭·예약. 자녀 정보는 수락 전 마스킹. 예약 시 비상연락·미성년위탁 동의 필수.',
        components: [{ role: '.pd-list', kind: 'list', label: '돌보미 카드(검증 배지)' }],
        description: [{ text: '검증 돌보미(성범죄경력·보험·교육)', target: '.pd-list' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '', result: '돌보미 목록', message: '', api: { endpoint: 'GET /app/caregivers', status: 200 } },
          { state: '빈데이터', trigger: '진입', guard: '매칭 없음', result: '대기 안내', message: '조건에 맞는 돌보미를 찾는 중이에요', placement: 'inline' },
          { state: '필수누락', trigger: '예약', guard: '비상연락/위탁동의 누락', result: '막음', message: '비상 연락처와 미성년 위탁 동의가 필요해요', placement: 'inline', priority: 'P0' },
          { state: '유효', trigger: '예약', guard: '동의 완료', result: '예약 요청(requested)', message: '', priority: 'P0', api: { endpoint: 'POST /app/respite-bookings', status: 201 } },
        ],
        interface: { reads: [{ id: 'listCaregivers', intent: '검증 돌보미', method: 'GET', path: '/app/caregivers', response: '{entities.Partner}[]', auth: 'Bearer', target: '.pd-list' }], writes: [{ id: 'createBooking', intent: '돌봄 예약', method: 'POST', path: '/app/respite-bookings', idempotencyKey: true, request: '{entities.RespiteBooking}', response: '{entities.RespiteBooking}', errors: [{ status: 422, when: '동의 누락', message: '필수 동의가 필요해요' }], auth: 'Bearer' }], events: [{ name: 'booking.requested', when: '예약 요청 시', payload: '{entities.RespiteBooking}' }] },
        flow: { to: [{ screen: 'SCR-PARENT-011', via: '예약 요청' }] },
      },
      {
        id: 'SCR-PARENT-011', label: '돌봄 예약 완료', href: 'p-respite-confirm.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P05'],
        context: '예약 요청 확인(수락 대기). 돌보미·일정·대상아이·요금 요약·보험/취소정책.',
        components: [{ role: '.pd-done', kind: 'state', label: '요청 완료' }, { role: '.pd-list', kind: 'list', label: '예약 요약' }],
        description: [{ text: '완료 상태·수락 대기', target: '.pd-done' }, { text: '돌보미·일정·요금', target: '.pd-list' }],
        cases: [{ state: '정상', trigger: '진입', guard: '예약 생성됨', result: '완료 요약', message: '', target: '.pd-done' }],
        interface: { reads: [{ id: 'getBooking', intent: '예약 상세', method: 'GET', path: '/app/respite-bookings/{id}', response: '{entities.RespiteBooking}', auth: 'Bearer' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-008', via: '내 예약' }] },
      },
      {
        id: 'SCR-PARENT-012', label: '안심 방문 예약', href: 'p-reservation.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P04'],
        context: '매장 방문 예약 — 시간대(한산)·동행인원·특이사항(보관·파기 고지)·필수/선택 동의.',
        components: [{ role: '.pd-form', kind: 'form', label: '예약 입력' }, { role: '.pd-check', kind: 'consent', label: '수집·공유 동의' }, { role: '.pd-cta-bar', kind: 'button', label: '예약 신청' }],
        description: [{ text: '시간대·인원·메모', target: '.pd-form' }, { text: '개인정보 수집(필수)·공유(선택)', target: '.pd-check' }],
        cases: [
          { state: '필수누락', trigger: '신청', guard: '수집 동의 미체크', result: '막음', message: '개인정보 수집·이용 동의가 필요해요', placement: 'inline', target: '.pd-check', priority: 'P1' },
          { state: '유효', trigger: '신청', guard: '정상', result: '예약 신청', message: '', priority: 'P0', api: { endpoint: 'POST /app/visit-reservations', status: 201 } },
        ],
        interface: { reads: [], writes: [{ id: 'createReservation', intent: '방문 예약', method: 'POST', path: '/app/visit-reservations', idempotencyKey: true, response: '{ id:string, status:string }', auth: 'Bearer', target: '.pd-form' }], events: [{ name: 'reservation.created', when: '신청 시', payload: '{ storeId, at, party }' }] },
        flow: { to: [{ screen: 'SCR-PARENT-013', via: '예약 신청' }] },
      },
      {
        id: 'SCR-PARENT-013', label: '예약 신청 완료', href: 'p-reservation-confirm.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P04'],
        context: '방문 예약 접수 확인(직원 알림 준비). 매장·시간·인원·전달사항 요약.',
        components: [{ role: '.pd-done', kind: 'state', label: '신청 완료' }, { role: '.pd-list', kind: 'list', label: '예약 요약' }],
        description: [{ text: '접수 확인', target: '.pd-done' }, { text: '매장·시간·전달사항', target: '.pd-list' }],
        cases: [{ state: '정상', trigger: '진입', guard: '접수됨', result: '완료 요약', message: '', target: '.pd-done' }],
        interface: { reads: [], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-001', via: '홈' }] },
      },
      {
        id: 'SCR-PARENT-014', label: '치료 예약', href: 'p-therapy.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P06'],
        context: '치료사 세션 예약 — 방식·일시·사전메모·공유 동의. 의료 아닌 발달 지원 고지.',
        components: [{ role: '.pd-form', kind: 'form', label: '치료 예약 입력' }, { role: '.pd-cta-bar', kind: 'button', label: '예약 요청' }],
        description: [{ text: '방식·일시·메모·동의', target: '.pd-form' }],
        cases: [
          { state: '필수누락', trigger: '요청', guard: '정보공유 동의 누락', result: '막음', message: '치료사와 정보 공유 동의가 필요해요', placement: 'inline', priority: 'P1' },
          { state: '유효', trigger: '요청', guard: '정상', result: '예약 요청', message: '', priority: 'P0', api: { endpoint: 'POST /app/therapy-bookings', status: 201 } },
        ],
        interface: { reads: [], writes: [{ id: 'createTherapy', intent: '치료 예약', method: 'POST', path: '/app/therapy-bookings', idempotencyKey: true, response: '{ id:string, status:string }', auth: 'Bearer', target: '.pd-form' }], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-015', via: '예약 요청' }] },
      },
      {
        id: 'SCR-PARENT-015', label: '치료 예약 완료', href: 'p-therapy-confirm.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P06'],
        context: '치료 예약 접수(치료사 배정 준비). 의료 고지.',
        components: [{ role: '.pd-done', kind: 'state', label: '요청 완료' }],
        description: [{ text: '치료사·방식·일시 요약', target: '.pd-done' }],
        cases: [{ state: '정상', trigger: '진입', guard: '', result: '완료 요약', message: '', target: '.pd-done' }],
        interface: { reads: [], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-006', via: '자녀 허브' }] },
      },
      {
        id: 'SCR-PARENT-016', label: '동행 요청', href: 'p-companion.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P07'],
        context: '또래 부모 무급 품앗이 동행 — 상대·일정·장소·인사메시지·동의.',
        components: [{ role: '.pd-form', kind: 'form', label: '동행 요청 입력' }, { role: '.pd-cta-bar', kind: 'button', label: '요청 보내기' }],
        description: [{ text: '상대·일정·장소·메시지', target: '.pd-form' }],
        cases: [
          { state: '유효', trigger: '요청', guard: '동의 완료', result: '요청 전송(수락 대기)', message: '', priority: 'P0', api: { endpoint: 'POST /app/companions', status: 201 } },
        ],
        interface: { reads: [], writes: [{ id: 'createCompanion', intent: '동행 요청', method: 'POST', path: '/app/companions', response: '{ id:string }', auth: 'Bearer' }], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-017', via: '요청 전송' }] },
      },
      {
        id: 'SCR-PARENT-017', label: '요청 전송 완료', href: 'p-companion-complete.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P07'],
        context: '동행 요청 전송 확인(상대 수락 대기).',
        components: [{ role: '.pd-done', kind: 'state', label: '전송 완료' }],
        description: [{ text: '상대·일정·장소 요약', target: '.pd-done' }],
        cases: [{ state: '정상', trigger: '진입', guard: '', result: '완료 요약', message: '', target: '.pd-done' }],
        interface: { reads: [], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-040', via: '알림' }] },
      },
      {
        id: 'SCR-PARENT-018', label: '1:1 상담', href: 'p-consult.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P08'],
        context: '치료사 1:1 채팅 상담 — 암호화·봇 응답 표기·세션 예약 연계.',
        components: [{ role: '.pd-chatlog', kind: 'chat', label: '상담 대화' }, { role: '.pd-comment-bar', kind: 'input', label: '메시지 입력' }],
        description: [{ text: '대화(암호화·봇 표기)', target: '.pd-chatlog' }, { text: '메시지 입력', target: '.pd-comment-bar' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '로그인', result: '대화 로드', message: '', api: { endpoint: 'GET /app/consult', status: 200 } },
          { state: '권한없음', trigger: '메시지', guard: '무료·비로그인', result: '도담패스 유도', message: '1:1 상담은 도담 패스로 열려요', placement: 'inline', priority: 'P1' },
        ],
        interface: { reads: [{ id: 'getConsult', intent: '상담 대화', method: 'GET', path: '/app/consult', response: '{ messages:object[] }', auth: 'Bearer' }], writes: [{ id: 'sendConsult', intent: '메시지 전송', method: 'POST', path: '/app/consult/messages', auth: 'Bearer', target: '.pd-comment-bar' }], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-014', via: '세션 예약' }] },
      },
      {
        id: 'SCR-PARENT-019', label: '우리 아이 살펴보기', href: 'p-self-check.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P10'],
        context: '비진단 자기점검(G2) — 비진단 고지 동의 게이트(스킵불가)·금칙어 필터·결과=상담 권고+자원.',
        components: [{ role: '.pd-check', kind: 'consent', label: '비진단 고지 동의(필수)' }, { role: '.pd-list', kind: 'list', label: '문항' }, { role: '.pd-cta-bar', kind: 'button', label: '결과 보기' }],
        description: [{ text: '비진단 고지 동의(스킵불가)', target: '.pd-check' }, { text: '문항(yes/no·scale)', target: '.pd-list' }],
        cases: [
          { state: '필수누락', trigger: '결과', guard: '비진단 고지 미동의', result: '막음', message: '비진단 안내 확인이 필요해요(진단이 아닌 자기점검)', placement: 'inline', target: '.pd-check', priority: 'P0' },
          { state: '유효', trigger: '결과', guard: '동의·응답', result: '상담 권고 결과', message: '진단이 아니에요 — 전문 상담을 권해요', placement: 'inline', priority: 'P0', api: { endpoint: 'POST /app/self-checks/{id}/submit', status: 200 } },
          { state: '권한없음', trigger: '진입', guard: 'license 미검증 템플릿', result: '준비 중', message: '이 도구는 검증 완료 후 제공돼요', placement: 'inline', priority: 'P1' },
        ],
        interface: { reads: [{ id: 'getTemplate', intent: '자가진단 문항', method: 'GET', path: '/app/self-checks/{id}', response: '{entities.SelfCheckTemplate}', auth: 'Bearer' }], writes: [{ id: 'submitCheck', intent: '응답 제출', method: 'POST', path: '/app/self-checks/{id}/submit', response: '{ result:string, referral:boolean }', errors: [{ status: 422, when: '비진단 동의 없음', message: '고지 동의가 필요해요' }], auth: 'Bearer', target: '.pd-check' }], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-014', via: '치료 권고' }, { screen: 'SCR-PARENT-004', via: '안심매장 권고' }] },
      },
      {
        id: 'SCR-PARENT-020', label: '시그널 카드', href: 'p-signal-card.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P11'],
        context: '해바라기 배려요청 카드 + QR 토큰. 전체화면(Wake Lock). 직원은 ?verify 로 발급일·체크리스트 확인.',
        components: [{ role: '.pd-signal-card', kind: 'card', label: '해바라기 시그널 카드' }, { role: '.pd-signal-full', kind: 'button', label: '크게 보여주기' }],
        description: [{ text: '배려 문구·QR·토큰', target: '.pd-signal-card' }, { text: '전체화면 표시', target: '.pd-signal-full' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '', result: '카드 표시', message: '', target: '.pd-signal-card' },
          { state: '에러', trigger: '크게보기', guard: 'Wake Lock 미지원', result: '밝기 안내', message: '화면을 밝게 유지해 주세요', placement: 'inline', priority: 'P2' },
        ],
        interface: { reads: [{ id: 'getSignalCard', intent: '시그널 카드', method: 'GET', path: '/app/signal-card', response: '{ need:string, token:string, issuedAt:string }', auth: 'Bearer', target: '.pd-signal-card' }], writes: [], events: [] },
        flow: { to: [] },
      },
      {
        id: 'SCR-PARENT-021', label: '긴급 도움(SOS)', href: 'p-sos.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P12'],
        context: '현장 긴급 — 상시 119/112 실연결·상황유형·비상연락 원탭. 취소/종료=알림 기록. 전 화면 FAB 진입.',
        components: [{ role: '.pd-call-btn', kind: 'button', label: '119/112 전화' }, { role: '.pd-list', kind: 'list', label: '비상 연락망' }],
        description: [{ text: '119·112 즉시 전화', target: '.pd-call-btn' }, { text: '상황유형·비상연락', target: '.pd-list' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '', result: '긴급 화면', message: '', target: '.pd-call-btn' },
          { state: '정상', trigger: '종료', guard: '상황 종료', result: '알림 기록', message: '안전 알림을 기록했어요', placement: 'toast', api: { endpoint: 'POST /app/sos', status: 201 } },
        ],
        interface: { reads: [], writes: [{ id: 'logSos', intent: 'SOS 기록', method: 'POST', path: '/app/sos', response: '{ id:string }', auth: 'Bearer', target: '.pd-list' }], events: [{ name: 'sos.raised', when: 'SOS 발생', payload: '{ type, at, contacts }' }] },
        flow: { to: [{ screen: 'SCR-PARENT-044', via: '비상연락 설정' }] },
      },
      {
        id: 'SCR-PARENT-022', label: '돌보미 지원', href: 'p-caregiver.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-T01'],
        context: '부모앱 내 공급자(돌보미) 온보딩 진입 — 5단계 검증 안내·성범죄경력 조회 동의·민감정보 암호화.',
        components: [{ role: '.pd-list', kind: 'list', label: '검증 절차' }, { role: '.pd-form', kind: 'form', label: '기본 정보' }, { role: '.pd-check', kind: 'consent', label: '조회·암호화 동의' }],
        description: [{ text: '5단계 검증', target: '.pd-list' }, { text: '성범죄경력 조회 동의(필수)', target: '.pd-check' }],
        cases: [
          { state: '필수누락', trigger: '제출', guard: '조회 동의 미체크', result: '막음', message: '성범죄경력 조회 동의가 필요해요', placement: 'inline', target: '.pd-check', priority: 'P0' },
          { state: '유효', trigger: '제출', guard: '동의 완료', result: '지원 접수(검증 대기)', message: '', priority: 'P0', api: { endpoint: 'POST /app/caregiver-applications', status: 201 } },
        ],
        interface: { reads: [], writes: [{ id: 'applyCaregiver', intent: '돌보미 지원', method: 'POST', path: '/app/caregiver-applications', response: '{ id:string, status:string }', auth: 'Bearer', target: '.pd-form' }], events: [] },
        flow: { to: [] },
      },
      {
        id: 'SCR-PARENT-023', label: '외출 안심 일지', href: 'p-diary.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P13'],
        context: '방문 사후 기록 — 마음상태·만족 5L·메모. 방문완료 전이 시 +150P.',
        components: [{ role: '.pd-form', kind: 'form', label: '일지 입력' }, { role: '.pd-cta-bar', kind: 'button', label: '일지 등록' }],
        description: [{ text: '상태·만족·메모', target: '.pd-form' }],
        cases: [{ state: '유효', trigger: '등록', guard: '정상', result: '일지 저장·포인트', message: '일지를 등록했어요 (+150P)', placement: 'toast', priority: 'P0', api: { endpoint: 'POST /app/diary', status: 201 } }],
        interface: { reads: [], writes: [{ id: 'createDiary', intent: '일지 등록', method: 'POST', path: '/app/diary', response: '{ id:string, pointsEarned:number }', auth: 'Bearer' }], events: [{ name: 'points.earned', when: '일지 등록', payload: '{ delta:150, reason:"diary" }' }] },
        flow: { to: [{ screen: 'SCR-PARENT-008', via: '마이' }] },
      },
      {
        id: 'SCR-PARENT-024', label: '안심 후기 작성', href: 'p-review.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P14'],
        context: '5L 안심지표 후기(별점 아님)·경험메모 필수·익명. 등록 +50P·코인 +3. 로그인 게이트.',
        components: [{ role: '.pd-list', kind: 'list', label: '5L 슬라이더' }, { role: '.pd-cta-bar', kind: 'button', label: '후기 등록' }],
        description: [{ text: '5L 안심지표', target: '.pd-list' }],
        cases: [
          { state: '권한없음', trigger: '진입', guard: '비로그인', result: '로그인 유도', message: '후기는 로그인이 필요해요', placement: 'inline', priority: 'P1' },
          { state: '필수누락', trigger: '등록', guard: '경험메모 없음', result: '막음', message: '경험 메모를 적어주세요', placement: 'inline', priority: 'P1' },
          { state: '유효', trigger: '등록', guard: '정상', result: '후기 등록·보상', message: '후기를 등록했어요 (+50P·코인 +3)', placement: 'toast', priority: 'P0', api: { endpoint: 'POST /app/stores/{id}/reviews', status: 201 } },
        ],
        interface: { reads: [], writes: [{ id: 'createReview', intent: '안심 후기', method: 'POST', path: '/app/stores/{id}/reviews', request: '{entities.StoreReview}', response: '{entities.StoreReview}', auth: 'Bearer', target: '.pd-list' }], events: [{ name: 'review.created', when: '후기 등록', payload: '{entities.StoreReview}' }] },
        flow: { to: [{ screen: 'SCR-PARENT-005', via: '매장 상세' }] },
      },
      {
        id: 'SCR-PARENT-025', label: '도담 지갑', href: 'p-wallet.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P19'],
        context: '코인/포인트/등급·교환. 코인=폐쇄형·현금 환급 불가·유효기간 12개월.',
        components: [{ role: '.pd-herocard', kind: 'card', label: '잔액·등급' }, { role: '.pd-list', kind: 'list', label: '적립·교환·내역' }],
        description: [{ text: '코인·포인트·등급', target: '.pd-herocard' }, { text: '교환 품목·내역', target: '.pd-list' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '로그인', result: '지갑', message: '', api: { endpoint: 'GET /app/wallet', status: 200 } },
          { state: '필수누락', trigger: '교환', guard: '코인 부족', result: '막음', message: '코인이 부족해요', placement: 'inline', priority: 'P2' },
          { state: '유효', trigger: '교환', guard: '코인 충분', result: '교환·차감', message: '교환했어요', placement: 'toast', priority: 'P0', api: { endpoint: 'POST /app/wallet/redeem', status: 200 } },
        ],
        interface: { reads: [{ id: 'getWallet', intent: '지갑', method: 'GET', path: '/app/wallet', response: '{entities.Wallet}', auth: 'Bearer', target: '.pd-herocard' }], writes: [{ id: 'redeem', intent: '코인 교환', method: 'POST', path: '/app/wallet/redeem', idempotencyKey: true, errors: [{ status: 422, when: '코인 부족', message: '코인이 부족해요' }], auth: 'Bearer' }], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-041', via: '도담패스' }] },
      },
      {
        id: 'SCR-PARENT-026', label: '커뮤니티 글', href: 'p-community-post.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P15'],
        context: '커뮤니티 글 상세·댓글·반응·신고.',
        components: [{ role: '.pd-list', kind: 'list', label: '댓글' }, { role: '.pd-comment-bar', kind: 'input', label: '댓글 입력' }],
        description: [{ text: '본문·댓글', target: '.pd-list' }, { text: '댓글 작성', target: '.pd-comment-bar' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '', result: '글·댓글', message: '', api: { endpoint: 'GET /app/community/{id}', status: 200 } },
          { state: '권한없음', trigger: '댓글', guard: '무료·비로그인', result: '도담패스/로그인 유도', message: '댓글은 로그인·도담 패스로 열려요', placement: 'inline', priority: 'P1' },
        ],
        interface: { reads: [{ id: 'getPost', intent: '글 상세', method: 'GET', path: '/app/community/{id}', response: '{entities.CommunityPost}', auth: 'Optional' }], writes: [{ id: 'addComment', intent: '댓글', method: 'POST', path: '/app/community/{id}/comments', auth: 'Bearer', target: '.pd-comment-bar' }], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-007', via: '목록' }] },
      },
      {
        id: 'SCR-PARENT-027', label: '안심장소 제안', href: 'p-community-propose.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P15'],
        context: '부모 안심장소 제안(인증 파이프라인) — 사진 저작권 동의(G3). 검수→매장 등록.',
        components: [{ role: '.pd-form', kind: 'form', label: '제안 폼' }, { role: '.pd-check', kind: 'consent', label: '사진 저작권 확인' }],
        description: [{ text: '장소·유형·안심포인트', target: '.pd-form' }, { text: '사진 저작권(직접촬영/동의)', target: '.pd-check' }],
        cases: [
          { state: '필수누락', trigger: '접수', guard: '저작권 미확인', result: '막음', message: '사진 저작권 확인이 필요해요', placement: 'inline', target: '.pd-check', priority: 'P1' },
          { state: '유효', trigger: '접수', guard: '정상', result: '제안 접수(검수 대기)', message: '제안이 접수됐어요. 검수 후 등록됩니다', placement: 'toast', priority: 'P0', api: { endpoint: 'POST /app/place-submissions', status: 201 } },
        ],
        interface: { reads: [], writes: [{ id: 'submitPlace', intent: '장소 제안', method: 'POST', path: '/app/place-submissions', request: '{entities.PlaceSubmission}', response: '{entities.PlaceSubmission}', auth: 'Bearer', target: '.pd-form' }], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-007', via: '커뮤니티' }] },
      },
      {
        id: 'SCR-PARENT-028', label: '전문가에게 질문', href: 'p-community-ask.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P15'],
        context: '발달·심리 전문가 Q&A 접수.',
        components: [{ role: '.pd-form', kind: 'form', label: '질문 폼' }],
        description: [{ text: '분야·질문', target: '.pd-form' }],
        cases: [{ state: '유효', trigger: '등록', guard: '로그인', result: '질문 접수', message: '질문을 등록했어요', placement: 'toast', priority: 'P0', api: { endpoint: 'POST /app/community/ask', status: 201 } }],
        interface: { reads: [], writes: [{ id: 'askExpert', intent: '전문가 질문', method: 'POST', path: '/app/community/ask', auth: 'Bearer' }], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-007', via: '커뮤니티' }] },
      },
      {
        id: 'SCR-PARENT-029', label: '아빠교실', href: 'p-community-dadclass.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P15'],
        context: '아빠교실 회차 신청 — open 회차·정원.',
        components: [{ role: '.pd-list', kind: 'list', label: '회차 목록' }],
        description: [{ text: '회차·정원·신청', target: '.pd-list' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '', result: '회차 목록', message: '', api: { endpoint: 'GET /app/dad-class', status: 200 } },
          { state: '필수누락', trigger: '신청', guard: '정원 초과', result: '막음', message: '정원이 찼어요', placement: 'inline', priority: 'P2' },
          { state: '유효', trigger: '신청', guard: '잔여 있음', result: '신청 접수', message: '신청했어요', placement: 'toast', priority: 'P0', api: { endpoint: 'POST /app/dad-class/{id}/apply', status: 201 } },
        ],
        interface: { reads: [{ id: 'listSessions', intent: '회차', method: 'GET', path: '/app/dad-class', response: '{ sessions:object[] }', auth: 'Optional', target: '.pd-list' }], writes: [{ id: 'applySession', intent: '회차 신청', method: 'POST', path: '/app/dad-class/{id}/apply', idempotencyKey: true, errors: [{ status: 409, when: '정원 초과', message: '정원이 찼어요' }], auth: 'Bearer' }], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-007', via: '커뮤니티' }] },
      },
      {
        id: 'SCR-PARENT-030', label: '앰배서더 후기', href: 'p-ambassador.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-T09'],
        context: '주간 미션·대가성 후기. 병원·의원은 평점 없이 경험만(의료법 G4)·대가성 고지.',
        components: [{ role: '.pd-segment', kind: 'tab', label: '카페식당/병원 대상' }, { role: '.pd-form', kind: 'form', label: '경험 후기' }],
        description: [{ text: '대상(활동비/자발)', target: '.pd-segment' }, { text: '경험 태그·메모', target: '.pd-form' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '앰배서더', result: '미션·대상', message: '', api: { endpoint: 'GET /app/ambassador', status: 200 } },
          { state: '유효', trigger: '제출', guard: '병원=무평점', result: '후기 제출(검수 대기)', message: '제출했어요. 검수 후 반영됩니다', placement: 'toast', priority: 'P0', api: { endpoint: 'POST /app/affinity-reviews', status: 201 } },
        ],
        interface: { reads: [], writes: [{ id: 'submitAffinity', intent: '친화도 후기', method: 'POST', path: '/app/affinity-reviews', request: '{entities.AffinityReview}', response: '{entities.AffinityReview}', errors: [{ status: 422, when: '병원에 평점 입력', message: '병원·의원은 평점을 남길 수 없어요(의료법)' }], auth: 'Bearer', target: '.pd-form' }], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-007', via: '커뮤니티' }] },
      },
      {
        id: 'SCR-PARENT-031', label: '장소 모음', href: 'p-lists.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P17'],
        context: '장소모음(책장) 핵심 소셜 — 내모음/팔로잉/구독/탐색. 별점·순위 없음.',
        components: [{ role: '.pd-segment', kind: 'tab', label: '모음 탭' }, { role: '.pd-list', kind: 'list', label: '모음·이웃' }],
        description: [{ text: '내모음/팔로잉/구독/탐색', target: '.pd-segment' }, { text: '모음 카드·이웃', target: '.pd-list' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '', result: '모음 목록', message: '', api: { endpoint: 'GET /app/lists', status: 200 } },
          { state: '비로그인', trigger: '내모음', guard: '세션 없음', result: '로그인 유도', message: '내 모음은 로그인이 필요해요', placement: 'inline' },
        ],
        interface: { reads: [{ id: 'listLists', intent: '장소 모음', method: 'GET', path: '/app/lists', response: '{entities.StoreList}[]', auth: 'Optional', target: '.pd-list' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-032', via: '모음' }, { screen: 'SCR-PARENT-046', via: '이웃' }] },
      },
      {
        id: 'SCR-PARENT-032', label: '장소 모음 상세', href: 'p-list-detail.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P17'],
        context: '모음 열람·구독·담긴 장소(메모). 별점/순위 없음.',
        components: [{ role: '.pd-banner', kind: 'banner', label: '구독' }, { role: '.pd-list', kind: 'list', label: '담긴 장소' }],
        description: [{ text: '구독', target: '.pd-banner' }, { text: '담긴 장소·메모', target: '.pd-list' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '', result: '모음 상세', message: '', api: { endpoint: 'GET /app/lists/{id}', status: 200 } },
          { state: '유효', trigger: '구독', guard: '로그인', result: '구독', message: '구독했어요', placement: 'toast', api: { endpoint: 'POST /app/lists/{id}/subscribe', status: 200 } },
        ],
        interface: { reads: [{ id: 'getList', intent: '모음 상세', method: 'GET', path: '/app/lists/{id}', response: '{entities.StoreList}', auth: 'Optional' }], writes: [{ id: 'subscribe', intent: '모음 구독', method: 'POST', path: '/app/lists/{id}/subscribe', auth: 'Bearer', target: '.pd-banner' }], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-005', via: '장소' }] },
      },
      {
        id: 'SCR-PARENT-033', label: '동네 이벤트', href: 'p-event.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P18'],
        context: '지역 통합 이벤트 상세 — 일시·장소·대상·정원·신청/길찾기.',
        components: [{ role: '.pd-list', kind: 'list', label: '이벤트 정보' }, { role: '.pd-cta-bar', kind: 'button', label: '신청·길찾기' }],
        description: [{ text: '일시·장소·대상·정원', target: '.pd-list' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '', result: '이벤트 상세', message: '', api: { endpoint: 'GET /app/events/{id}', status: 200 } },
          { state: '필수누락', trigger: '신청', guard: '정원 초과', result: '막음', message: '정원이 찼어요', placement: 'inline', priority: 'P2' },
        ],
        interface: { reads: [{ id: 'getEvent', intent: '이벤트', method: 'GET', path: '/app/events/{id}', response: '{ event:object }', auth: 'Optional' }], writes: [{ id: 'applyEvent', intent: '이벤트 신청', method: 'POST', path: '/app/events/{id}/apply', idempotencyKey: true, auth: 'Bearer' }], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-001', via: '홈' }] },
      },
      {
        id: 'SCR-PARENT-034', label: '돌봄 이야기', href: 'p-stories.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P16'],
        context: '콘텐츠 허브 — 오늘의 추천·주제별·5대영역·고충 유형.',
        components: [{ role: '.pd-feature', kind: 'card', label: '추천 콘텐츠' }, { role: '.pd-tiles', kind: 'tiles', label: '주제별' }],
        description: [{ text: '추천', target: '.pd-feature' }, { text: '주제별 타일', target: '.pd-tiles' }],
        cases: [{ state: '정상', trigger: '진입', guard: '', result: '콘텐츠 허브', message: '', api: { endpoint: 'GET /app/stories', status: 200 } }],
        interface: { reads: [{ id: 'listStories', intent: '콘텐츠', method: 'GET', path: '/app/stories', response: '{entities.StoryArticle}[]', auth: 'Optional', target: '.pd-feature' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-035', via: '주제별' }, { screen: 'SCR-PARENT-036', via: '아티클' }] },
      },
      {
        id: 'SCR-PARENT-035', label: '주제별 정보', href: 'p-stories-topics.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P16'],
        context: '3대축×서브토픽 필터·가이드 카드.',
        components: [{ role: '.pd-list', kind: 'list', label: '가이드 목록' }],
        description: [{ text: '축·서브토픽·가이드', target: '.pd-list' }],
        cases: [{ state: '정상', trigger: '진입', guard: '', result: '주제 목록', message: '' }],
        interface: { reads: [{ id: 'listGuides', intent: '가이드', method: 'GET', path: '/app/stories/guides', response: '{entities.StoryArticle}[]', auth: 'Optional', target: '.pd-list' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-038', via: '가이드' }] },
      },
      {
        id: 'SCR-PARENT-036', label: '돌봄 이야기(아티클)', href: 'p-story-article.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P16'],
        context: '고충 유형 콘텐츠 — 본문·반응·저장·추천.',
        components: [{ role: '.pd-wf-text', kind: 'text', label: '본문' }, { role: '.pd-list', kind: 'list', label: '추천' }],
        description: [{ text: '본문·반응', target: '.pd-wf-text' }, { text: '관련 글', target: '.pd-list' }],
        cases: [{ state: '정상', trigger: '진입', guard: '', result: '아티클', message: '' }, { state: '유효', trigger: '저장', guard: '로그인', result: '북마크', message: '저장했어요', placement: 'toast' }],
        interface: { reads: [{ id: 'getArticle', intent: '아티클', method: 'GET', path: '/app/stories/articles/{id}', response: '{entities.StoryArticle}', auth: 'Optional' }], writes: [{ id: 'saveStory', intent: '저장', method: 'POST', path: '/app/stories/{id}/save', auth: 'Bearer' }], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-039', via: '유형' }] },
      },
      {
        id: 'SCR-PARENT-037', label: '발행 콘텐츠', href: 'p-story-feed.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P16'],
        context: '발행 콘텐츠 상세(story_articles) — 본문·반응·공유·저장.',
        components: [{ role: '.pd-wf-text', kind: 'text', label: '본문' }],
        description: [{ text: '본문·반응·저장', target: '.pd-wf-text' }],
        cases: [{ state: '정상', trigger: '진입', guard: '', result: '콘텐츠', message: '' }],
        interface: { reads: [{ id: 'getFeed', intent: '발행 콘텐츠', method: 'GET', path: '/app/stories/feed/{id}', response: '{entities.StoryArticle}', auth: 'Optional' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-034', via: '이야기' }] },
      },
      {
        id: 'SCR-PARENT-038', label: '주제별 가이드', href: 'p-story-guide.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P16'],
        context: '3대축 정보 가이드 — 본문·출처·관련.',
        components: [{ role: '.pd-wf-text', kind: 'text', label: '가이드 본문' }],
        description: [{ text: '본문·출처', target: '.pd-wf-text' }],
        cases: [{ state: '정상', trigger: '진입', guard: '', result: '가이드', message: '' }],
        interface: { reads: [{ id: 'getGuide', intent: '가이드', method: 'GET', path: '/app/stories/guides/{id}', response: '{entities.StoryArticle}', auth: 'Optional' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-035', via: '주제별' }] },
      },
      {
        id: 'SCR-PARENT-039', label: '유형별 이야기', href: 'p-story-type.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P16'],
        context: '고충 유형별 글목록.',
        components: [{ role: '.pd-list', kind: 'list', label: '유형별 글' }],
        description: [{ text: '유형 글 리스트', target: '.pd-list' }],
        cases: [{ state: '정상', trigger: '진입', guard: '', result: '유형 목록', message: '' }],
        interface: { reads: [{ id: 'listByType', intent: '유형 글', method: 'GET', path: '/app/stories/types/{id}', response: '{entities.StoryArticle}[]', auth: 'Optional', target: '.pd-list' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-036', via: '아티클' }] },
      },
      {
        id: 'SCR-PARENT-040', label: '알림', href: 'p-notifications.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P22'],
        context: '알림함 — 매칭·댓글·행사. 서버+로컬 병합·자동 읽음.',
        components: [{ role: '.pd-list', kind: 'list', label: '알림 목록' }],
        description: [{ text: '종류별 알림', target: '.pd-list' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '로그인', result: '알림·자동읽음', message: '', api: { endpoint: 'GET /app/notifications', status: 200 } },
          { state: '빈데이터', trigger: '진입', guard: '알림 없음', result: '빈 상태', message: '새 알림이 없어요', placement: 'inline', target: '.pd-list' },
        ],
        interface: { reads: [{ id: 'listNotifications', intent: '알림', method: 'GET', path: '/app/notifications', response: '{entities.Notification}[]', auth: 'Bearer', target: '.pd-list' }], writes: [{ id: 'markRead', intent: '읽음 처리', method: 'POST', path: '/app/notifications/read', auth: 'Bearer' }], events: [] },
        flow: { to: [] },
      },
      {
        id: 'SCR-PARENT-041', label: '도담 패스', href: 'p-my-premium.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P21'],
        context: '월 990원 후원(실 PG 미연동·상태/UI만·수동). 소프트게이트 기능 안내.',
        components: [{ role: '.pd-done', kind: 'state', label: '후원 상태' }, { role: '.pd-list', kind: 'list', label: '열리는 기능' }],
        description: [{ text: '후원 상태', target: '.pd-done' }, { text: '열리는 기능', target: '.pd-list' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '로그인', result: '후원 상태', message: '', api: { endpoint: 'GET /app/membership', status: 200 } },
          { state: '정상', trigger: '신청', guard: 'PG 미연동', result: '신청 상태 기록', message: '신청 상태를 기록했어요(실 결제는 준비 중)', placement: 'inline', priority: 'P1', api: { endpoint: 'POST /app/membership/subscribe', status: 200 } },
        ],
        interface: { reads: [{ id: 'getMembership', intent: '멤버십', method: 'GET', path: '/app/membership', response: '{entities.Membership}', auth: 'Bearer', target: '.pd-done' }], writes: [{ id: 'subscribePass', intent: '도담패스 신청', method: 'POST', path: '/app/membership/subscribe', response: '{entities.Membership}', auth: 'Bearer' }], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-007', via: '커뮤니티' }] },
      },
      {
        id: 'SCR-PARENT-042', label: '개인정보 처리방침', href: 'p-my-privacy.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P23'],
        context: 'PIPA 고지 — 최소수집·민감정보·제3자·위탁·법정대리인·보유파기·권리.',
        components: [{ role: '.pd-legal', kind: 'doc', label: '처리방침 본문' }],
        description: [{ text: '처리방침 조항', target: '.pd-legal' }],
        cases: [{ state: '정상', trigger: '진입', guard: '', result: '방침 본문', message: '' }],
        interface: { reads: [{ id: 'getPrivacy', intent: '처리방침', method: 'GET', path: '/app/legal/privacy', response: '{ body:string }', auth: 'None', target: '.pd-legal' }], writes: [], events: [] },
        flow: { to: [] },
      },
      {
        id: 'SCR-PARENT-043', label: '약관·앱 정보', href: 'p-my-terms.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P23'],
        context: '이용약관 요약·앱버전·서비스 지역(일산·파주/고양).',
        components: [{ role: '.pd-legal', kind: 'doc', label: '약관 본문' }],
        description: [{ text: '중개·책임·코인', target: '.pd-legal' }],
        cases: [{ state: '정상', trigger: '진입', guard: '', result: '약관 본문', message: '' }],
        interface: { reads: [{ id: 'getTerms', intent: '약관', method: 'GET', path: '/app/legal/terms', response: '{ body:string }', auth: 'None', target: '.pd-legal' }], writes: [], events: [] },
        flow: { to: [] },
      },
      {
        id: 'SCR-PARENT-044', label: '알림·비상연락 설정', href: 'p-my-notif-settings.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P22'],
        context: '푸시 토글·SOS 비상 연락처.',
        components: [{ role: '.pd-toggle', kind: 'toggle', label: '알림 토글' }, { role: '.pd-list', kind: 'list', label: '비상 연락망' }],
        description: [{ text: '알림 수신 토글', target: '.pd-toggle' }, { text: '비상 연락처(SOS 연계)', target: '.pd-list' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '로그인', result: '설정 로드', message: '', api: { endpoint: 'GET /app/settings/notifications', status: 200 } },
          { state: '정상', trigger: '토글', guard: '', result: '저장', message: '설정을 저장했어요', placement: 'toast', api: { endpoint: 'PATCH /app/settings/notifications', status: 200 } },
        ],
        interface: { reads: [{ id: 'getNotifSettings', intent: '알림 설정', method: 'GET', path: '/app/settings/notifications', response: '{ push:object, emergency:object[] }', auth: 'Bearer' }], writes: [{ id: 'updateNotifSettings', intent: '설정 저장', method: 'PATCH', path: '/app/settings/notifications', auth: 'Bearer', target: '.pd-toggle' }], events: [] },
        flow: { to: [] },
      },
      {
        id: 'SCR-PARENT-045', label: '저장한 이야기', href: 'p-my-saved-stories.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P16'],
        context: '북마크한 콘텐츠.',
        components: [{ role: '.pd-list', kind: 'list', label: '저장 목록' }],
        description: [{ text: '저장 콘텐츠', target: '.pd-list' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '로그인', result: '저장 목록', message: '', api: { endpoint: 'GET /app/saved-stories', status: 200 } },
          { state: '빈데이터', trigger: '진입', guard: '저장 없음', result: '빈 상태', message: '저장한 이야기가 없어요', placement: 'inline', target: '.pd-list' },
        ],
        interface: { reads: [{ id: 'listSaved', intent: '저장 목록', method: 'GET', path: '/app/saved-stories', response: '{entities.StoryArticle}[]', auth: 'Bearer', target: '.pd-list' }], writes: [], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-036', via: '아티클' }] },
      },
      {
        id: 'SCR-PARENT-046', label: '보호자 프로필', href: 'p-user-profile.html',
        surface: 'parent', entry: false, status: 'confirmed', designed: false, figmaLink: '', reqIds: ['REQ-P20'],
        context: '공개 프로필·소셜 — 팔로우·공개 장소모음. 자녀 배려 배지는 로그인자만·비공개 마스킹.',
        components: [{ role: '.pd-herocard', kind: 'card', label: '프로필 헤더' }, { role: '.pd-list', kind: 'list', label: '공개 모음' }],
        description: [{ text: '닉네임·지역·팔로우', target: '.pd-herocard' }, { text: '공개 장소모음', target: '.pd-list' }],
        cases: [
          { state: '정상', trigger: '진입', guard: '', result: '공개 프로필', message: '', api: { endpoint: 'GET /app/u/{id}', status: 200 } },
          { state: '권한없음', trigger: '배려배지', guard: '비로그인', result: '마스킹', message: '자녀 배려 정보는 로그인 후 볼 수 있어요', placement: 'inline' },
          { state: '유효', trigger: '팔로우', guard: '로그인', result: '팔로우', message: '', api: { endpoint: 'POST /app/u/{id}/follow', status: 200 } },
        ],
        interface: { reads: [{ id: 'getUser', intent: '공개 프로필', method: 'GET', path: '/app/u/{id}', response: '{ profile:{entities.Profile}, lists:{entities.StoreList}[] }', auth: 'Optional' }], writes: [{ id: 'follow', intent: '팔로우', method: 'POST', path: '/app/u/{id}/follow', auth: 'Bearer', target: '.pd-herocard' }], events: [] },
        flow: { to: [{ screen: 'SCR-PARENT-032', via: '모음' }] },
      },
    ],
  },
];
window.PDK_SCREENS = window.PLANDECK_SCREENS;
